build:
  project: fontes/uninfe.sln
  publish_nuget: true

nuget:
  account_feed: true
  project_feed: true

deploy:
  - provider: NuGet
    server: http://www.nuget.org
    api_key:
      secure: c531b238-e827-431a-bb50-04a7c7543833
    skip_symbols: true
    artifact: uninfe.nupkg