before_build:
  - nuget restore fontes/uninfe.sln
  - nuget spec fontes/uninfe.sln

after_build:
  - nuget pack fontes/uninfe.nuspec

artifacts:
  - path: '*.nupkg'

build:
  project: fontes/uninfe.sln
  publish_nuget: true

nuget:
  account_feed: true
  project_feed: true

deploy:
  - provider: NuGet
    api_key:
      secure: c531b238-e827-431a-bb50-04a7c7543833
    artifact: '*.nupkg'