//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace NFe.Components.br.gov.pr.londrina.testeiss.h {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ModuloEmissorNFSeBinding", Namespace="http://iss.londrina.pr.gov.br/ws/v1_03")]
    public partial class ModuloEmissorNFSe : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GerarNotaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelarNotaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarNfseServicoPrestadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarRpsServicoPrestadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarCadastroContribuinteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ModuloEmissorNFSe() {
            this.Url = global::NFe.Components.Properties.Settings.Default.NFe_Components_br_gov_pr_londrina_testeiss_h_ModuloEmissorNFSe;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GerarNotaCompletedEventHandler GerarNotaCompleted;
        
        /// <remarks/>
        public event CancelarNotaCompletedEventHandler CancelarNotaCompleted;
        
        /// <remarks/>
        public event ConsultarNfseServicoPrestadoCompletedEventHandler ConsultarNfseServicoPrestadoCompleted;
        
        /// <remarks/>
        public event ConsultarRpsServicoPrestadoCompletedEventHandler ConsultarRpsServicoPrestadoCompleted;
        
        /// <remarks/>
        public event ConsultarCadastroContribuinteCompletedEventHandler ConsultarCadastroContribuinteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://iss.londrina.pr.gov.br/ws/v1_03#GerarNota", RequestNamespace="http://iss.londrina.pr.gov.br/ws/v1_03", ResponseNamespace="http://iss.londrina.pr.gov.br/ws/v1_03", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("RetornoNota")]
        public tcRetornoNota GerarNota(tcDescricaoRps DescricaoRps, [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] out tcEstruturaDescricaoErros[] Mensagens) {
            object[] results = this.Invoke("GerarNota", new object[] {
                        DescricaoRps});
            Mensagens = ((tcEstruturaDescricaoErros[])(results[1]));
            return ((tcRetornoNota)(results[0]));
        }
        
        /// <remarks/>
        public void GerarNotaAsync(tcDescricaoRps DescricaoRps) {
            this.GerarNotaAsync(DescricaoRps, null);
        }
        
        /// <remarks/>
        public void GerarNotaAsync(tcDescricaoRps DescricaoRps, object userState) {
            if ((this.GerarNotaOperationCompleted == null)) {
                this.GerarNotaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGerarNotaOperationCompleted);
            }
            this.InvokeAsync("GerarNota", new object[] {
                        DescricaoRps}, this.GerarNotaOperationCompleted, userState);
        }
        
        private void OnGerarNotaOperationCompleted(object arg) {
            if ((this.GerarNotaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GerarNotaCompleted(this, new GerarNotaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://iss.londrina.pr.gov.br/ws/v1_03#CancelarNota", RequestNamespace="http://iss.londrina.pr.gov.br/ws/v1_03", ResponseNamespace="http://iss.londrina.pr.gov.br/ws/v1_03", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("RetornoNota")]
        public tcRetornoNota CancelarNota(tcDescricaoCancelaNota DescricaoCancelaNota, [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] out tcEstruturaDescricaoErros[] Mensagens) {
            object[] results = this.Invoke("CancelarNota", new object[] {
                        DescricaoCancelaNota});
            Mensagens = ((tcEstruturaDescricaoErros[])(results[1]));
            return ((tcRetornoNota)(results[0]));
        }
        
        /// <remarks/>
        public void CancelarNotaAsync(tcDescricaoCancelaNota DescricaoCancelaNota) {
            this.CancelarNotaAsync(DescricaoCancelaNota, null);
        }
        
        /// <remarks/>
        public void CancelarNotaAsync(tcDescricaoCancelaNota DescricaoCancelaNota, object userState) {
            if ((this.CancelarNotaOperationCompleted == null)) {
                this.CancelarNotaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelarNotaOperationCompleted);
            }
            this.InvokeAsync("CancelarNota", new object[] {
                        DescricaoCancelaNota}, this.CancelarNotaOperationCompleted, userState);
        }
        
        private void OnCancelarNotaOperationCompleted(object arg) {
            if ((this.CancelarNotaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelarNotaCompleted(this, new CancelarNotaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://iss.londrina.pr.gov.br/ws/v1_03#ConsultarNfseServicoPrestado", RequestNamespace="http://iss.londrina.pr.gov.br/ws/v1_03", ResponseNamespace="http://iss.londrina.pr.gov.br/ws/v1_03", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("RetornoNota")]
        public string ConsultarNfseServicoPrestado(tcConsultarNfseServicoPrestadoEnvio ConsultarNfseServicoPrestadoEnvio, [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] out tcEstruturaDescricaoErros[] Mensagens) {
            object[] results = this.Invoke("ConsultarNfseServicoPrestado", new object[] {
                        ConsultarNfseServicoPrestadoEnvio});
            Mensagens = ((tcEstruturaDescricaoErros[])(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarNfseServicoPrestadoAsync(tcConsultarNfseServicoPrestadoEnvio ConsultarNfseServicoPrestadoEnvio) {
            this.ConsultarNfseServicoPrestadoAsync(ConsultarNfseServicoPrestadoEnvio, null);
        }
        
        /// <remarks/>
        public void ConsultarNfseServicoPrestadoAsync(tcConsultarNfseServicoPrestadoEnvio ConsultarNfseServicoPrestadoEnvio, object userState) {
            if ((this.ConsultarNfseServicoPrestadoOperationCompleted == null)) {
                this.ConsultarNfseServicoPrestadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarNfseServicoPrestadoOperationCompleted);
            }
            this.InvokeAsync("ConsultarNfseServicoPrestado", new object[] {
                        ConsultarNfseServicoPrestadoEnvio}, this.ConsultarNfseServicoPrestadoOperationCompleted, userState);
        }
        
        private void OnConsultarNfseServicoPrestadoOperationCompleted(object arg) {
            if ((this.ConsultarNfseServicoPrestadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarNfseServicoPrestadoCompleted(this, new ConsultarNfseServicoPrestadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://iss.londrina.pr.gov.br/ws/v1_03#ConsultarRpsServicoPrestado", RequestNamespace="http://iss.londrina.pr.gov.br/ws/v1_03", ResponseNamespace="http://iss.londrina.pr.gov.br/ws/v1_03", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("RetornoNota")]
        public string ConsultarRpsServicoPrestado(tcConsultarRpsServicoPrestadoEnvio ConsultarRpsServicoPrestadoEnvio, [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] out tcEstruturaDescricaoErros[] Mensagens) {
            object[] results = this.Invoke("ConsultarRpsServicoPrestado", new object[] {
                        ConsultarRpsServicoPrestadoEnvio});
            Mensagens = ((tcEstruturaDescricaoErros[])(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarRpsServicoPrestadoAsync(tcConsultarRpsServicoPrestadoEnvio ConsultarRpsServicoPrestadoEnvio) {
            this.ConsultarRpsServicoPrestadoAsync(ConsultarRpsServicoPrestadoEnvio, null);
        }
        
        /// <remarks/>
        public void ConsultarRpsServicoPrestadoAsync(tcConsultarRpsServicoPrestadoEnvio ConsultarRpsServicoPrestadoEnvio, object userState) {
            if ((this.ConsultarRpsServicoPrestadoOperationCompleted == null)) {
                this.ConsultarRpsServicoPrestadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarRpsServicoPrestadoOperationCompleted);
            }
            this.InvokeAsync("ConsultarRpsServicoPrestado", new object[] {
                        ConsultarRpsServicoPrestadoEnvio}, this.ConsultarRpsServicoPrestadoOperationCompleted, userState);
        }
        
        private void OnConsultarRpsServicoPrestadoOperationCompleted(object arg) {
            if ((this.ConsultarRpsServicoPrestadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarRpsServicoPrestadoCompleted(this, new ConsultarRpsServicoPrestadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://iss.londrina.pr.gov.br/ws/v1_03#ConsultarCadastroContribuinte", RequestNamespace="http://iss.londrina.pr.gov.br/ws/v1_03", ResponseNamespace="http://iss.londrina.pr.gov.br/ws/v1_03", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("RetornoCadastro")]
        public string ConsultarCadastroContribuinte(tcConsultarCadastroContribuinteEnvio ConsultarCadastroContribuinteEnvio, [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] out tcEstruturaDescricaoErros[] Mensagens) {
            object[] results = this.Invoke("ConsultarCadastroContribuinte", new object[] {
                        ConsultarCadastroContribuinteEnvio});
            Mensagens = ((tcEstruturaDescricaoErros[])(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarCadastroContribuinteAsync(tcConsultarCadastroContribuinteEnvio ConsultarCadastroContribuinteEnvio) {
            this.ConsultarCadastroContribuinteAsync(ConsultarCadastroContribuinteEnvio, null);
        }
        
        /// <remarks/>
        public void ConsultarCadastroContribuinteAsync(tcConsultarCadastroContribuinteEnvio ConsultarCadastroContribuinteEnvio, object userState) {
            if ((this.ConsultarCadastroContribuinteOperationCompleted == null)) {
                this.ConsultarCadastroContribuinteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarCadastroContribuinteOperationCompleted);
            }
            this.InvokeAsync("ConsultarCadastroContribuinte", new object[] {
                        ConsultarCadastroContribuinteEnvio}, this.ConsultarCadastroContribuinteOperationCompleted, userState);
        }
        
        private void OnConsultarCadastroContribuinteOperationCompleted(object arg) {
            if ((this.ConsultarCadastroContribuinteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarCadastroContribuinteCompleted(this, new ConsultarCadastroContribuinteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iss.londrina.pr.gov.br/ws/v1_03")]
    public partial class tcDescricaoRps {
        
        private int ccmField;
        
        private string cnpjField;
        
        private string cpfField;
        
        private string senhaField;
        
        private string aliquotaField;
        
        private int servicoField;
        
        private string codigo_obraField;
        
        private string obra_artField;
        
        private string situacaoField;
        
        private string valorField;
        
        private string baseField;
        
        private string irField;
        
        private string pisField;
        
        private string cofinsField;
        
        private string csllField;
        
        private string inssField;
        
        private string retencao_issField;
        
        private int incentivo_fiscalField;
        
        private bool incentivo_fiscalFieldSpecified;
        
        private string cod_municipio_prestacao_servicoField;
        
        private string cod_pais_prestacao_servicoField;
        
        private string cod_municipio_incidenciaField;
        
        private string descricaoNFField;
        
        private int tomador_tipoField;
        
        private string tomador_cnpjField;
        
        private string tomador_emailField;
        
        private string tomador_ieField;
        
        private string tomador_imField;
        
        private string tomador_razaoField;
        
        private string tomador_enderecoField;
        
        private string tomador_numeroField;
        
        private string tomador_complementoField;
        
        private string tomador_bairroField;
        
        private string tomador_CEPField;
        
        private string tomador_cod_cidadeField;
        
        private string tomador_foneField;
        
        private string tomador_ramalField;
        
        private string tomador_faxField;
        
        private int rps_numField;
        
        private bool rps_numFieldSpecified;
        
        private string rps_serieField;
        
        private int rps_tipoField;
        
        private bool rps_tipoFieldSpecified;
        
        private int rps_diaField;
        
        private bool rps_diaFieldSpecified;
        
        private int rps_mesField;
        
        private bool rps_mesFieldSpecified;
        
        private int rps_anoField;
        
        private bool rps_anoFieldSpecified;
        
        private int nfse_substituidaField;
        
        private bool nfse_substituidaFieldSpecified;
        
        private int rps_substituidoField;
        
        private bool rps_substituidoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ccm {
            get {
                return this.ccmField;
            }
            set {
                this.ccmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string aliquota {
            get {
                return this.aliquotaField;
            }
            set {
                this.aliquotaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int servico {
            get {
                return this.servicoField;
            }
            set {
                this.servicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigo_obra {
            get {
                return this.codigo_obraField;
            }
            set {
                this.codigo_obraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string obra_art {
            get {
                return this.obra_artField;
            }
            set {
                this.obra_artField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string situacao {
            get {
                return this.situacaoField;
            }
            set {
                this.situacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @base {
            get {
                return this.baseField;
            }
            set {
                this.baseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ir {
            get {
                return this.irField;
            }
            set {
                this.irField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pis {
            get {
                return this.pisField;
            }
            set {
                this.pisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cofins {
            get {
                return this.cofinsField;
            }
            set {
                this.cofinsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string csll {
            get {
                return this.csllField;
            }
            set {
                this.csllField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inss {
            get {
                return this.inssField;
            }
            set {
                this.inssField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string retencao_iss {
            get {
                return this.retencao_issField;
            }
            set {
                this.retencao_issField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int incentivo_fiscal {
            get {
                return this.incentivo_fiscalField;
            }
            set {
                this.incentivo_fiscalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool incentivo_fiscalSpecified {
            get {
                return this.incentivo_fiscalFieldSpecified;
            }
            set {
                this.incentivo_fiscalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cod_municipio_prestacao_servico {
            get {
                return this.cod_municipio_prestacao_servicoField;
            }
            set {
                this.cod_municipio_prestacao_servicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cod_pais_prestacao_servico {
            get {
                return this.cod_pais_prestacao_servicoField;
            }
            set {
                this.cod_pais_prestacao_servicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cod_municipio_incidencia {
            get {
                return this.cod_municipio_incidenciaField;
            }
            set {
                this.cod_municipio_incidenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descricaoNF {
            get {
                return this.descricaoNFField;
            }
            set {
                this.descricaoNFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int tomador_tipo {
            get {
                return this.tomador_tipoField;
            }
            set {
                this.tomador_tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tomador_cnpj {
            get {
                return this.tomador_cnpjField;
            }
            set {
                this.tomador_cnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tomador_email {
            get {
                return this.tomador_emailField;
            }
            set {
                this.tomador_emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tomador_ie {
            get {
                return this.tomador_ieField;
            }
            set {
                this.tomador_ieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tomador_im {
            get {
                return this.tomador_imField;
            }
            set {
                this.tomador_imField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tomador_razao {
            get {
                return this.tomador_razaoField;
            }
            set {
                this.tomador_razaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tomador_endereco {
            get {
                return this.tomador_enderecoField;
            }
            set {
                this.tomador_enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tomador_numero {
            get {
                return this.tomador_numeroField;
            }
            set {
                this.tomador_numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tomador_complemento {
            get {
                return this.tomador_complementoField;
            }
            set {
                this.tomador_complementoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tomador_bairro {
            get {
                return this.tomador_bairroField;
            }
            set {
                this.tomador_bairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tomador_CEP {
            get {
                return this.tomador_CEPField;
            }
            set {
                this.tomador_CEPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tomador_cod_cidade {
            get {
                return this.tomador_cod_cidadeField;
            }
            set {
                this.tomador_cod_cidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tomador_fone {
            get {
                return this.tomador_foneField;
            }
            set {
                this.tomador_foneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tomador_ramal {
            get {
                return this.tomador_ramalField;
            }
            set {
                this.tomador_ramalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tomador_fax {
            get {
                return this.tomador_faxField;
            }
            set {
                this.tomador_faxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int rps_num {
            get {
                return this.rps_numField;
            }
            set {
                this.rps_numField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rps_numSpecified {
            get {
                return this.rps_numFieldSpecified;
            }
            set {
                this.rps_numFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rps_serie {
            get {
                return this.rps_serieField;
            }
            set {
                this.rps_serieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int rps_tipo {
            get {
                return this.rps_tipoField;
            }
            set {
                this.rps_tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rps_tipoSpecified {
            get {
                return this.rps_tipoFieldSpecified;
            }
            set {
                this.rps_tipoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int rps_dia {
            get {
                return this.rps_diaField;
            }
            set {
                this.rps_diaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rps_diaSpecified {
            get {
                return this.rps_diaFieldSpecified;
            }
            set {
                this.rps_diaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int rps_mes {
            get {
                return this.rps_mesField;
            }
            set {
                this.rps_mesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rps_mesSpecified {
            get {
                return this.rps_mesFieldSpecified;
            }
            set {
                this.rps_mesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int rps_ano {
            get {
                return this.rps_anoField;
            }
            set {
                this.rps_anoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rps_anoSpecified {
            get {
                return this.rps_anoFieldSpecified;
            }
            set {
                this.rps_anoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int nfse_substituida {
            get {
                return this.nfse_substituidaField;
            }
            set {
                this.nfse_substituidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nfse_substituidaSpecified {
            get {
                return this.nfse_substituidaFieldSpecified;
            }
            set {
                this.nfse_substituidaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int rps_substituido {
            get {
                return this.rps_substituidoField;
            }
            set {
                this.rps_substituidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rps_substituidoSpecified {
            get {
                return this.rps_substituidoFieldSpecified;
            }
            set {
                this.rps_substituidoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iss.londrina.pr.gov.br/ws/v1_03")]
    public partial class tcConsultarCadastroContribuinteEnvio {
        
        private int ccmField;
        
        private string cnpjField;
        
        private string cpfField;
        
        private string senhaField;
        
        private string cnpj_cpf_cadastroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ccm {
            get {
                return this.ccmField;
            }
            set {
                this.ccmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cnpj_cpf_cadastro {
            get {
                return this.cnpj_cpf_cadastroField;
            }
            set {
                this.cnpj_cpf_cadastroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iss.londrina.pr.gov.br/ws/v1_03")]
    public partial class tcConsultarRpsServicoPrestadoEnvio {
        
        private int ccmField;
        
        private string cnpjField;
        
        private string cpfField;
        
        private string senhaField;
        
        private int numero_rpsField;
        
        private int dia_rpsField;
        
        private int mes_rpsField;
        
        private int ano_rpsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ccm {
            get {
                return this.ccmField;
            }
            set {
                this.ccmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int numero_rps {
            get {
                return this.numero_rpsField;
            }
            set {
                this.numero_rpsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int dia_rps {
            get {
                return this.dia_rpsField;
            }
            set {
                this.dia_rpsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int mes_rps {
            get {
                return this.mes_rpsField;
            }
            set {
                this.mes_rpsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ano_rps {
            get {
                return this.ano_rpsField;
            }
            set {
                this.ano_rpsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iss.londrina.pr.gov.br/ws/v1_03")]
    public partial class tcConsultarNfseServicoPrestadoEnvio {
        
        private int ccmField;
        
        private string cnpjField;
        
        private string cpfField;
        
        private string senhaField;
        
        private int numero_nfseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ccm {
            get {
                return this.ccmField;
            }
            set {
                this.ccmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int numero_nfse {
            get {
                return this.numero_nfseField;
            }
            set {
                this.numero_nfseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iss.londrina.pr.gov.br/ws/v1_03")]
    public partial class tcDescricaoCancelaNota {
        
        private int ccmField;
        
        private string cnpjField;
        
        private string cpfField;
        
        private string senhaField;
        
        private int notaField;
        
        private int cod_cancelamentoField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ccm {
            get {
                return this.ccmField;
            }
            set {
                this.ccmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int nota {
            get {
                return this.notaField;
            }
            set {
                this.notaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cod_cancelamento {
            get {
                return this.cod_cancelamentoField;
            }
            set {
                this.cod_cancelamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iss.londrina.pr.gov.br/ws/v1_03")]
    public partial class tcEstruturaDescricaoErros {
        
        private string idField;
        
        private string descricaoProcessoField;
        
        private string descricaoErroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DescricaoProcesso {
            get {
                return this.descricaoProcessoField;
            }
            set {
                this.descricaoProcessoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DescricaoErro {
            get {
                return this.descricaoErroField;
            }
            set {
                this.descricaoErroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iss.londrina.pr.gov.br/ws/v1_03")]
    public partial class tcRetornoNota {
        
        private int resultadoField;
        
        private bool resultadoFieldSpecified;
        
        private int notaField;
        
        private bool notaFieldSpecified;
        
        private string autenticidadeField;
        
        private string linkImpressaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResultadoSpecified {
            get {
                return this.resultadoFieldSpecified;
            }
            set {
                this.resultadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Nota {
            get {
                return this.notaField;
            }
            set {
                this.notaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NotaSpecified {
            get {
                return this.notaFieldSpecified;
            }
            set {
                this.notaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string autenticidade {
            get {
                return this.autenticidadeField;
            }
            set {
                this.autenticidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LinkImpressao {
            get {
                return this.linkImpressaoField;
            }
            set {
                this.linkImpressaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GerarNotaCompletedEventHandler(object sender, GerarNotaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GerarNotaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GerarNotaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tcRetornoNota Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tcRetornoNota)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public tcEstruturaDescricaoErros[] Mensagens {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tcEstruturaDescricaoErros[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void CancelarNotaCompletedEventHandler(object sender, CancelarNotaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelarNotaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelarNotaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tcRetornoNota Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tcRetornoNota)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public tcEstruturaDescricaoErros[] Mensagens {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tcEstruturaDescricaoErros[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ConsultarNfseServicoPrestadoCompletedEventHandler(object sender, ConsultarNfseServicoPrestadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarNfseServicoPrestadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarNfseServicoPrestadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public tcEstruturaDescricaoErros[] Mensagens {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tcEstruturaDescricaoErros[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ConsultarRpsServicoPrestadoCompletedEventHandler(object sender, ConsultarRpsServicoPrestadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarRpsServicoPrestadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarRpsServicoPrestadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public tcEstruturaDescricaoErros[] Mensagens {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tcEstruturaDescricaoErros[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ConsultarCadastroContribuinteCompletedEventHandler(object sender, ConsultarCadastroContribuinteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarCadastroContribuinteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarCadastroContribuinteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public tcEstruturaDescricaoErros[] Mensagens {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tcEstruturaDescricaoErros[])(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591