<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.fazenda.pr.gov.br/wsdl/sefaws" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="LMCAutorizacao" targetNamespace="http://www.fazenda.pr.gov.br/wsdl/sefaws">
<wsdl:documentation>Livro de Movimentacao de Combustivel - Servico destinado a recepcao de mensagens.</wsdl:documentation>
  <wsdl:types>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.fazenda.pr.gov.br/wsdl/sefaws" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" attributeFormDefault="unqualified" elementFormDefault="unqualified" targetNamespace="http://www.fazenda.pr.gov.br/wsdl/sefaws">
			
  <xsd:element name="lmcAutorizacao" type="tns:lmcAutorizacao" />
			
  <xsd:complexType name="lmcAutorizacao">
				
    <xsd:sequence>
					
      <xsd:element maxOccurs="1" minOccurs="1" name="xmlDados">
						
        <xsd:complexType mixed="true">
							
          <xsd:sequence>
								
            <xsd:any />
							
          </xsd:sequence>
						
        </xsd:complexType>
					
      </xsd:element>
				
    </xsd:sequence>
			
  </xsd:complexType>
			
  <xsd:element name="lmcAutorizacaoResult" type="tns:lmcAutorizacaoResult" />
			
  <xsd:complexType name="lmcAutorizacaoResult">
				
    <xsd:sequence>
					<!-- <xsd:element minOccurs="1" maxOccurs="1" name="xmlDados" type="xmlDadosResult" /> -->
					
      <xsd:any />
				
    </xsd:sequence>
			
  </xsd:complexType>
			
  <xsd:complexType name="xmlDadosResult">
				
    <xsd:sequence>
					 
      <xsd:any />
				
    </xsd:sequence>
			
  </xsd:complexType>
		
</xsd:schema>
  </wsdl:types>
  <wsdl:message name="lmcAutorizacaoResult">
    <wsdl:part element="tns:lmcAutorizacaoResult" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="lmcAutorizacao">
    <wsdl:part element="tns:lmcAutorizacao" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="LMCWS">
    <wsdl:operation name="lmcAutorizacao">
<wsdl:documentation>Transmissao de Lote de LMC</wsdl:documentation>
      <wsdl:input message="tns:lmcAutorizacao" name="lmcAutorizacao">
    </wsdl:input>
      <wsdl:output message="tns:lmcAutorizacaoResult" name="lmcAutorizacaoResult">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="LMCWSServiceSoapBinding" type="tns:LMCWS">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="lmcAutorizacao">
      <soap12:operation soapAction="" style="document" />
      <wsdl:input name="lmcAutorizacao">
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output name="lmcAutorizacaoResult">
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="LMCAutorizacao">
<wsdl:documentation>Servico destinado a recepcao de mensagens de lote do LMC.</wsdl:documentation>
    <wsdl:port binding="tns:LMCWSServiceSoapBinding" name="LMCAutorizacaoServicePort">
      <soap12:address location="https://lmcws.fazenda.pr.gov.br/lmcws/AutorizacaoWS" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>