//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFe.Components.HAmargosaBA {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExcecaoDetalhes", Namespace="http://nfse.abrasf.org.br")]
    [System.SerializableAttribute()]
    public partial class ExcecaoDetalhes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComponenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClasseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoErroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoErroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivoErroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Componente {
            get {
                return this.ComponenteField;
            }
            set {
                if ((object.ReferenceEquals(this.ComponenteField, value) != true)) {
                    this.ComponenteField = value;
                    this.RaisePropertyChanged("Componente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Classe {
            get {
                return this.ClasseField;
            }
            set {
                if ((object.ReferenceEquals(this.ClasseField, value) != true)) {
                    this.ClasseField = value;
                    this.RaisePropertyChanged("Classe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Metodo {
            get {
                return this.MetodoField;
            }
            set {
                if ((object.ReferenceEquals(this.MetodoField, value) != true)) {
                    this.MetodoField = value;
                    this.RaisePropertyChanged("Metodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CodigoErro {
            get {
                return this.CodigoErroField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoErroField, value) != true)) {
                    this.CodigoErroField = value;
                    this.RaisePropertyChanged("CodigoErro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DescricaoErro {
            get {
                return this.DescricaoErroField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoErroField, value) != true)) {
                    this.DescricaoErroField = value;
                    this.RaisePropertyChanged("DescricaoErro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string MotivoErro {
            get {
                return this.MotivoErroField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoErroField, value) != true)) {
                    this.MotivoErroField = value;
                    this.RaisePropertyChanged("MotivoErro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nfse.abrasf.org.br", ConfigurationName="HAmargosaBA.Infse")]
    public interface Infse {
        
        // CODEGEN: Generating message contract since the wrapper name (RecepcionarLoteRpsRequest) of message RecepcionarLoteRpsRequest does not match the default value (RecepcionarLoteRps)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/Infse/RecepcionarLoteRps", ReplyAction="http://nfse.abrasf.org.br/Infse/RecepcionarLoteRpsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NFe.Components.HAmargosaBA.ExcecaoDetalhes), Action="http://nfse.abrasf.org.br/Infse/RecepcionarLoteRpsExcecaoDetalhesFault", Name="ExcecaoDetalhes")]
        NFe.Components.HAmargosaBA.RecepcionarLoteRpsResponse RecepcionarLoteRps(NFe.Components.HAmargosaBA.RecepcionarLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/Infse/RecepcionarLoteRps", ReplyAction="http://nfse.abrasf.org.br/Infse/RecepcionarLoteRpsResponse")]
        System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.RecepcionarLoteRpsResponse> RecepcionarLoteRpsAsync(NFe.Components.HAmargosaBA.RecepcionarLoteRpsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (RecepcionarLoteRpsSincronoRequest) of message RecepcionarLoteRpsSincronoRequest does not match the default value (RecepcionarLoteRpsSincrono)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/Infse/RecepcionarLoteRpsSincrono", ReplyAction="http://nfse.abrasf.org.br/Infse/RecepcionarLoteRpsSincronoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NFe.Components.HAmargosaBA.ExcecaoDetalhes), Action="http://nfse.abrasf.org.br/Infse/RecepcionarLoteRpsSincronoExcecaoDetalhesFault", Name="ExcecaoDetalhes")]
        NFe.Components.HAmargosaBA.RecepcionarLoteRpsSincronoResponse RecepcionarLoteRpsSincrono(NFe.Components.HAmargosaBA.RecepcionarLoteRpsSincronoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/Infse/RecepcionarLoteRpsSincrono", ReplyAction="http://nfse.abrasf.org.br/Infse/RecepcionarLoteRpsSincronoResponse")]
        System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.RecepcionarLoteRpsSincronoResponse> RecepcionarLoteRpsSincronoAsync(NFe.Components.HAmargosaBA.RecepcionarLoteRpsSincronoRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (GerarNfseRequest) of message GerarNfseRequest does not match the default value (GerarNfse)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/Infse/GerarNfse", ReplyAction="http://nfse.abrasf.org.br/Infse/GerarNfseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NFe.Components.HAmargosaBA.ExcecaoDetalhes), Action="http://nfse.abrasf.org.br/Infse/GerarNfseExcecaoDetalhesFault", Name="ExcecaoDetalhes")]
        NFe.Components.HAmargosaBA.GerarNfseResponse GerarNfse(NFe.Components.HAmargosaBA.GerarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/Infse/GerarNfse", ReplyAction="http://nfse.abrasf.org.br/Infse/GerarNfseResponse")]
        System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.GerarNfseResponse> GerarNfseAsync(NFe.Components.HAmargosaBA.GerarNfseRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (CancelarNfseRequest) of message CancelarNfseRequest does not match the default value (CancelarNfse)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/Infse/CancelarNfse", ReplyAction="http://nfse.abrasf.org.br/Infse/CancelarNfseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NFe.Components.HAmargosaBA.ExcecaoDetalhes), Action="http://nfse.abrasf.org.br/Infse/CancelarNfseExcecaoDetalhesFault", Name="ExcecaoDetalhes")]
        NFe.Components.HAmargosaBA.CancelarNfseResponse CancelarNfse(NFe.Components.HAmargosaBA.CancelarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/Infse/CancelarNfse", ReplyAction="http://nfse.abrasf.org.br/Infse/CancelarNfseResponse")]
        System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.CancelarNfseResponse> CancelarNfseAsync(NFe.Components.HAmargosaBA.CancelarNfseRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (SubstituirNfseRequest) of message SubstituirNfseRequest does not match the default value (SubstituirNfse)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/Infse/SubstituirNfse", ReplyAction="http://nfse.abrasf.org.br/Infse/SubstituirNfseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NFe.Components.HAmargosaBA.ExcecaoDetalhes), Action="http://nfse.abrasf.org.br/Infse/SubstituirNfseExcecaoDetalhesFault", Name="ExcecaoDetalhes")]
        NFe.Components.HAmargosaBA.SubstituirNfseResponse SubstituirNfse(NFe.Components.HAmargosaBA.SubstituirNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/Infse/SubstituirNfse", ReplyAction="http://nfse.abrasf.org.br/Infse/SubstituirNfseResponse")]
        System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.SubstituirNfseResponse> SubstituirNfseAsync(NFe.Components.HAmargosaBA.SubstituirNfseRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultarLoteRpsRequest) of message ConsultarLoteRpsRequest does not match the default value (ConsultarLoteRps)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/Infse/ConsultarLoteRps", ReplyAction="http://nfse.abrasf.org.br/Infse/ConsultarLoteRpsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NFe.Components.HAmargosaBA.ExcecaoDetalhes), Action="http://nfse.abrasf.org.br/Infse/ConsultarLoteRpsExcecaoDetalhesFault", Name="ExcecaoDetalhes")]
        NFe.Components.HAmargosaBA.ConsultarLoteRpsResponse ConsultarLoteRps(NFe.Components.HAmargosaBA.ConsultarLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/Infse/ConsultarLoteRps", ReplyAction="http://nfse.abrasf.org.br/Infse/ConsultarLoteRpsResponse")]
        System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.ConsultarLoteRpsResponse> ConsultarLoteRpsAsync(NFe.Components.HAmargosaBA.ConsultarLoteRpsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultarNfsePorRpsRequest) of message ConsultarNfsePorRpsRequest does not match the default value (ConsultarNfsePorRps)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/Infse/ConsultarNfsePorRps", ReplyAction="http://nfse.abrasf.org.br/Infse/ConsultarNfsePorRpsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NFe.Components.HAmargosaBA.ExcecaoDetalhes), Action="http://nfse.abrasf.org.br/Infse/ConsultarNfsePorRpsExcecaoDetalhesFault", Name="ExcecaoDetalhes")]
        NFe.Components.HAmargosaBA.ConsultarNfsePorRpsResponse ConsultarNfsePorRps(NFe.Components.HAmargosaBA.ConsultarNfsePorRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/Infse/ConsultarNfsePorRps", ReplyAction="http://nfse.abrasf.org.br/Infse/ConsultarNfsePorRpsResponse")]
        System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.ConsultarNfsePorRpsResponse> ConsultarNfsePorRpsAsync(NFe.Components.HAmargosaBA.ConsultarNfsePorRpsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultarNfseServicoPrestadoRequest) of message ConsultarNfseServicoPrestadoRequest does not match the default value (ConsultarNfseServicoPrestado)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/Infse/ConsultarNfseServicoPrestado", ReplyAction="http://nfse.abrasf.org.br/Infse/ConsultarNfseServicoPrestadoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NFe.Components.HAmargosaBA.ExcecaoDetalhes), Action="http://nfse.abrasf.org.br/Infse/ConsultarNfseServicoPrestadoExcecaoDetalhesFault", Name="ExcecaoDetalhes")]
        NFe.Components.HAmargosaBA.ConsultarNfseServicoPrestadoResponse ConsultarNfseServicoPrestado(NFe.Components.HAmargosaBA.ConsultarNfseServicoPrestadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/Infse/ConsultarNfseServicoPrestado", ReplyAction="http://nfse.abrasf.org.br/Infse/ConsultarNfseServicoPrestadoResponse")]
        System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.ConsultarNfseServicoPrestadoResponse> ConsultarNfseServicoPrestadoAsync(NFe.Components.HAmargosaBA.ConsultarNfseServicoPrestadoRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultarNfseServicoTomadoRequest) of message ConsultarNfseServicoTomadoRequest does not match the default value (ConsultarNfseServicoTomado)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/Infse/ConsultarNfseServicoTomado", ReplyAction="http://nfse.abrasf.org.br/Infse/ConsultarNfseServicoTomadoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NFe.Components.HAmargosaBA.ExcecaoDetalhes), Action="http://nfse.abrasf.org.br/Infse/ConsultarNfseServicoTomadoExcecaoDetalhesFault", Name="ExcecaoDetalhes")]
        NFe.Components.HAmargosaBA.ConsultarNfseServicoTomadoResponse ConsultarNfseServicoTomado(NFe.Components.HAmargosaBA.ConsultarNfseServicoTomadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/Infse/ConsultarNfseServicoTomado", ReplyAction="http://nfse.abrasf.org.br/Infse/ConsultarNfseServicoTomadoResponse")]
        System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.ConsultarNfseServicoTomadoResponse> ConsultarNfseServicoTomadoAsync(NFe.Components.HAmargosaBA.ConsultarNfseServicoTomadoRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultarNfsePorFaixaRequest) of message ConsultarNfsePorFaixaRequest does not match the default value (ConsultarNfsePorFaixa)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/Infse/ConsultarNfsePorFaixa", ReplyAction="http://nfse.abrasf.org.br/Infse/ConsultarNfsePorFaixaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NFe.Components.HAmargosaBA.ExcecaoDetalhes), Action="http://nfse.abrasf.org.br/Infse/ConsultarNfsePorFaixaExcecaoDetalhesFault", Name="ExcecaoDetalhes")]
        NFe.Components.HAmargosaBA.ConsultarNfsePorFaixaResponse ConsultarNfsePorFaixa(NFe.Components.HAmargosaBA.ConsultarNfsePorFaixaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/Infse/ConsultarNfsePorFaixa", ReplyAction="http://nfse.abrasf.org.br/Infse/ConsultarNfsePorFaixaResponse")]
        System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.ConsultarNfsePorFaixaResponse> ConsultarNfsePorFaixaAsync(NFe.Components.HAmargosaBA.ConsultarNfsePorFaixaRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (IncluirOutrasInformacoesNaNfseRequest) of message IncluirOutrasInformacoesNaNfseRequest does not match the default value (IncluirOutrasInformacoesNaNfse)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/Infse/IncluirOutrasInformacoesNaNfse", ReplyAction="http://nfse.abrasf.org.br/Infse/IncluirOutrasInformacoesNaNfseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NFe.Components.HAmargosaBA.ExcecaoDetalhes), Action="http://nfse.abrasf.org.br/Infse/IncluirOutrasInformacoesNaNfseExcecaoDetalhesFaul" +
            "t", Name="ExcecaoDetalhes")]
        NFe.Components.HAmargosaBA.IncluirOutrasInformacoesNaNfseResponse IncluirOutrasInformacoesNaNfse(NFe.Components.HAmargosaBA.IncluirOutrasInformacoesNaNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/Infse/IncluirOutrasInformacoesNaNfse", ReplyAction="http://nfse.abrasf.org.br/Infse/IncluirOutrasInformacoesNaNfseResponse")]
        System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.IncluirOutrasInformacoesNaNfseResponse> IncluirOutrasInformacoesNaNfseAsync(NFe.Components.HAmargosaBA.IncluirOutrasInformacoesNaNfseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class RecepcionarLoteRpsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public RecepcionarLoteRpsRequest() {
        }
        
        public RecepcionarLoteRpsRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class RecepcionarLoteRpsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public RecepcionarLoteRpsResponse() {
        }
        
        public RecepcionarLoteRpsResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsSincronoRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class RecepcionarLoteRpsSincronoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public RecepcionarLoteRpsSincronoRequest() {
        }
        
        public RecepcionarLoteRpsSincronoRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsSincronoResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class RecepcionarLoteRpsSincronoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public RecepcionarLoteRpsSincronoResponse() {
        }
        
        public RecepcionarLoteRpsSincronoResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GerarNfseRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class GerarNfseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public GerarNfseRequest() {
        }
        
        public GerarNfseRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GerarNfseResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class GerarNfseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public GerarNfseResponse() {
        }
        
        public GerarNfseResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarNfseRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class CancelarNfseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public CancelarNfseRequest() {
        }
        
        public CancelarNfseRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarNfseResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class CancelarNfseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public CancelarNfseResponse() {
        }
        
        public CancelarNfseResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubstituirNfseRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class SubstituirNfseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public SubstituirNfseRequest() {
        }
        
        public SubstituirNfseRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubstituirNfseResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class SubstituirNfseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public SubstituirNfseResponse() {
        }
        
        public SubstituirNfseResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarLoteRpsRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarLoteRpsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarLoteRpsRequest() {
        }
        
        public ConsultarLoteRpsRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarLoteRpsResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarLoteRpsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarLoteRpsResponse() {
        }
        
        public ConsultarLoteRpsResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorRpsRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfsePorRpsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfsePorRpsRequest() {
        }
        
        public ConsultarNfsePorRpsRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorRpsResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfsePorRpsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarNfsePorRpsResponse() {
        }
        
        public ConsultarNfsePorRpsResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseServicoPrestadoRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfseServicoPrestadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfseServicoPrestadoRequest() {
        }
        
        public ConsultarNfseServicoPrestadoRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseServicoPrestadoResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfseServicoPrestadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarNfseServicoPrestadoResponse() {
        }
        
        public ConsultarNfseServicoPrestadoResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseServicoTomadoRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfseServicoTomadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfseServicoTomadoRequest() {
        }
        
        public ConsultarNfseServicoTomadoRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseServicoTomadoResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfseServicoTomadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarNfseServicoTomadoResponse() {
        }
        
        public ConsultarNfseServicoTomadoResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorFaixaRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfsePorFaixaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfsePorFaixaRequest() {
        }
        
        public ConsultarNfsePorFaixaRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorFaixaResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfsePorFaixaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarNfsePorFaixaResponse() {
        }
        
        public ConsultarNfsePorFaixaResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IncluirOutrasInformacoesNaNfseRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class IncluirOutrasInformacoesNaNfseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string inscricaoMunicipalPrestador;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string numeroNfse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string codigoVerificacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string outrasInformacoes;
        
        public IncluirOutrasInformacoesNaNfseRequest() {
        }
        
        public IncluirOutrasInformacoesNaNfseRequest(string inscricaoMunicipalPrestador, string numeroNfse, string codigoVerificacao, string outrasInformacoes) {
            this.inscricaoMunicipalPrestador = inscricaoMunicipalPrestador;
            this.numeroNfse = numeroNfse;
            this.codigoVerificacao = codigoVerificacao;
            this.outrasInformacoes = outrasInformacoes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IncluirOutrasInformacoesNaNfseResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class IncluirOutrasInformacoesNaNfseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public IncluirOutrasInformacoesNaNfseResponse() {
        }
        
        public IncluirOutrasInformacoesNaNfseResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InfseChannel : NFe.Components.HAmargosaBA.Infse, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InfseClient : System.ServiceModel.ClientBase<NFe.Components.HAmargosaBA.Infse>, NFe.Components.HAmargosaBA.Infse {
        
        public InfseClient() {
        }
        
        public InfseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InfseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InfseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InfseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFe.Components.HAmargosaBA.RecepcionarLoteRpsResponse NFe.Components.HAmargosaBA.Infse.RecepcionarLoteRps(NFe.Components.HAmargosaBA.RecepcionarLoteRpsRequest request) {
            return base.Channel.RecepcionarLoteRps(request);
        }
        
        public string RecepcionarLoteRps(string nfseCabecMsg, string nfseDadosMsg) {
            NFe.Components.HAmargosaBA.RecepcionarLoteRpsRequest inValue = new NFe.Components.HAmargosaBA.RecepcionarLoteRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            NFe.Components.HAmargosaBA.RecepcionarLoteRpsResponse retVal = ((NFe.Components.HAmargosaBA.Infse)(this)).RecepcionarLoteRps(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.RecepcionarLoteRpsResponse> NFe.Components.HAmargosaBA.Infse.RecepcionarLoteRpsAsync(NFe.Components.HAmargosaBA.RecepcionarLoteRpsRequest request) {
            return base.Channel.RecepcionarLoteRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.RecepcionarLoteRpsResponse> RecepcionarLoteRpsAsync(string nfseCabecMsg, string nfseDadosMsg) {
            NFe.Components.HAmargosaBA.RecepcionarLoteRpsRequest inValue = new NFe.Components.HAmargosaBA.RecepcionarLoteRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NFe.Components.HAmargosaBA.Infse)(this)).RecepcionarLoteRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFe.Components.HAmargosaBA.RecepcionarLoteRpsSincronoResponse NFe.Components.HAmargosaBA.Infse.RecepcionarLoteRpsSincrono(NFe.Components.HAmargosaBA.RecepcionarLoteRpsSincronoRequest request) {
            return base.Channel.RecepcionarLoteRpsSincrono(request);
        }
        
        public string RecepcionarLoteRpsSincrono(string nfseCabecMsg, string nfseDadosMsg) {
            NFe.Components.HAmargosaBA.RecepcionarLoteRpsSincronoRequest inValue = new NFe.Components.HAmargosaBA.RecepcionarLoteRpsSincronoRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            NFe.Components.HAmargosaBA.RecepcionarLoteRpsSincronoResponse retVal = ((NFe.Components.HAmargosaBA.Infse)(this)).RecepcionarLoteRpsSincrono(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.RecepcionarLoteRpsSincronoResponse> NFe.Components.HAmargosaBA.Infse.RecepcionarLoteRpsSincronoAsync(NFe.Components.HAmargosaBA.RecepcionarLoteRpsSincronoRequest request) {
            return base.Channel.RecepcionarLoteRpsSincronoAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.RecepcionarLoteRpsSincronoResponse> RecepcionarLoteRpsSincronoAsync(string nfseCabecMsg, string nfseDadosMsg) {
            NFe.Components.HAmargosaBA.RecepcionarLoteRpsSincronoRequest inValue = new NFe.Components.HAmargosaBA.RecepcionarLoteRpsSincronoRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NFe.Components.HAmargosaBA.Infse)(this)).RecepcionarLoteRpsSincronoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFe.Components.HAmargosaBA.GerarNfseResponse NFe.Components.HAmargosaBA.Infse.GerarNfse(NFe.Components.HAmargosaBA.GerarNfseRequest request) {
            return base.Channel.GerarNfse(request);
        }
        
        public string GerarNfse(string nfseCabecMsg, string nfseDadosMsg) {
            NFe.Components.HAmargosaBA.GerarNfseRequest inValue = new NFe.Components.HAmargosaBA.GerarNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            NFe.Components.HAmargosaBA.GerarNfseResponse retVal = ((NFe.Components.HAmargosaBA.Infse)(this)).GerarNfse(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.GerarNfseResponse> NFe.Components.HAmargosaBA.Infse.GerarNfseAsync(NFe.Components.HAmargosaBA.GerarNfseRequest request) {
            return base.Channel.GerarNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.GerarNfseResponse> GerarNfseAsync(string nfseCabecMsg, string nfseDadosMsg) {
            NFe.Components.HAmargosaBA.GerarNfseRequest inValue = new NFe.Components.HAmargosaBA.GerarNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NFe.Components.HAmargosaBA.Infse)(this)).GerarNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFe.Components.HAmargosaBA.CancelarNfseResponse NFe.Components.HAmargosaBA.Infse.CancelarNfse(NFe.Components.HAmargosaBA.CancelarNfseRequest request) {
            return base.Channel.CancelarNfse(request);
        }
        
        public string CancelarNfse(string nfseCabecMsg, string nfseDadosMsg) {
            NFe.Components.HAmargosaBA.CancelarNfseRequest inValue = new NFe.Components.HAmargosaBA.CancelarNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            NFe.Components.HAmargosaBA.CancelarNfseResponse retVal = ((NFe.Components.HAmargosaBA.Infse)(this)).CancelarNfse(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.CancelarNfseResponse> NFe.Components.HAmargosaBA.Infse.CancelarNfseAsync(NFe.Components.HAmargosaBA.CancelarNfseRequest request) {
            return base.Channel.CancelarNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.CancelarNfseResponse> CancelarNfseAsync(string nfseCabecMsg, string nfseDadosMsg) {
            NFe.Components.HAmargosaBA.CancelarNfseRequest inValue = new NFe.Components.HAmargosaBA.CancelarNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NFe.Components.HAmargosaBA.Infse)(this)).CancelarNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFe.Components.HAmargosaBA.SubstituirNfseResponse NFe.Components.HAmargosaBA.Infse.SubstituirNfse(NFe.Components.HAmargosaBA.SubstituirNfseRequest request) {
            return base.Channel.SubstituirNfse(request);
        }
        
        public string SubstituirNfse(string nfseCabecMsg, string nfseDadosMsg) {
            NFe.Components.HAmargosaBA.SubstituirNfseRequest inValue = new NFe.Components.HAmargosaBA.SubstituirNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            NFe.Components.HAmargosaBA.SubstituirNfseResponse retVal = ((NFe.Components.HAmargosaBA.Infse)(this)).SubstituirNfse(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.SubstituirNfseResponse> NFe.Components.HAmargosaBA.Infse.SubstituirNfseAsync(NFe.Components.HAmargosaBA.SubstituirNfseRequest request) {
            return base.Channel.SubstituirNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.SubstituirNfseResponse> SubstituirNfseAsync(string nfseCabecMsg, string nfseDadosMsg) {
            NFe.Components.HAmargosaBA.SubstituirNfseRequest inValue = new NFe.Components.HAmargosaBA.SubstituirNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NFe.Components.HAmargosaBA.Infse)(this)).SubstituirNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFe.Components.HAmargosaBA.ConsultarLoteRpsResponse NFe.Components.HAmargosaBA.Infse.ConsultarLoteRps(NFe.Components.HAmargosaBA.ConsultarLoteRpsRequest request) {
            return base.Channel.ConsultarLoteRps(request);
        }
        
        public string ConsultarLoteRps(string nfseCabecMsg, string nfseDadosMsg) {
            NFe.Components.HAmargosaBA.ConsultarLoteRpsRequest inValue = new NFe.Components.HAmargosaBA.ConsultarLoteRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            NFe.Components.HAmargosaBA.ConsultarLoteRpsResponse retVal = ((NFe.Components.HAmargosaBA.Infse)(this)).ConsultarLoteRps(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.ConsultarLoteRpsResponse> NFe.Components.HAmargosaBA.Infse.ConsultarLoteRpsAsync(NFe.Components.HAmargosaBA.ConsultarLoteRpsRequest request) {
            return base.Channel.ConsultarLoteRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.ConsultarLoteRpsResponse> ConsultarLoteRpsAsync(string nfseCabecMsg, string nfseDadosMsg) {
            NFe.Components.HAmargosaBA.ConsultarLoteRpsRequest inValue = new NFe.Components.HAmargosaBA.ConsultarLoteRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NFe.Components.HAmargosaBA.Infse)(this)).ConsultarLoteRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFe.Components.HAmargosaBA.ConsultarNfsePorRpsResponse NFe.Components.HAmargosaBA.Infse.ConsultarNfsePorRps(NFe.Components.HAmargosaBA.ConsultarNfsePorRpsRequest request) {
            return base.Channel.ConsultarNfsePorRps(request);
        }
        
        public string ConsultarNfsePorRps(string nfseCabecMsg, string nfseDadosMsg) {
            NFe.Components.HAmargosaBA.ConsultarNfsePorRpsRequest inValue = new NFe.Components.HAmargosaBA.ConsultarNfsePorRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            NFe.Components.HAmargosaBA.ConsultarNfsePorRpsResponse retVal = ((NFe.Components.HAmargosaBA.Infse)(this)).ConsultarNfsePorRps(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.ConsultarNfsePorRpsResponse> NFe.Components.HAmargosaBA.Infse.ConsultarNfsePorRpsAsync(NFe.Components.HAmargosaBA.ConsultarNfsePorRpsRequest request) {
            return base.Channel.ConsultarNfsePorRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.ConsultarNfsePorRpsResponse> ConsultarNfsePorRpsAsync(string nfseCabecMsg, string nfseDadosMsg) {
            NFe.Components.HAmargosaBA.ConsultarNfsePorRpsRequest inValue = new NFe.Components.HAmargosaBA.ConsultarNfsePorRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NFe.Components.HAmargosaBA.Infse)(this)).ConsultarNfsePorRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFe.Components.HAmargosaBA.ConsultarNfseServicoPrestadoResponse NFe.Components.HAmargosaBA.Infse.ConsultarNfseServicoPrestado(NFe.Components.HAmargosaBA.ConsultarNfseServicoPrestadoRequest request) {
            return base.Channel.ConsultarNfseServicoPrestado(request);
        }
        
        public string ConsultarNfseServicoPrestado(string nfseCabecMsg, string nfseDadosMsg) {
            NFe.Components.HAmargosaBA.ConsultarNfseServicoPrestadoRequest inValue = new NFe.Components.HAmargosaBA.ConsultarNfseServicoPrestadoRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            NFe.Components.HAmargosaBA.ConsultarNfseServicoPrestadoResponse retVal = ((NFe.Components.HAmargosaBA.Infse)(this)).ConsultarNfseServicoPrestado(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.ConsultarNfseServicoPrestadoResponse> NFe.Components.HAmargosaBA.Infse.ConsultarNfseServicoPrestadoAsync(NFe.Components.HAmargosaBA.ConsultarNfseServicoPrestadoRequest request) {
            return base.Channel.ConsultarNfseServicoPrestadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.ConsultarNfseServicoPrestadoResponse> ConsultarNfseServicoPrestadoAsync(string nfseCabecMsg, string nfseDadosMsg) {
            NFe.Components.HAmargosaBA.ConsultarNfseServicoPrestadoRequest inValue = new NFe.Components.HAmargosaBA.ConsultarNfseServicoPrestadoRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NFe.Components.HAmargosaBA.Infse)(this)).ConsultarNfseServicoPrestadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFe.Components.HAmargosaBA.ConsultarNfseServicoTomadoResponse NFe.Components.HAmargosaBA.Infse.ConsultarNfseServicoTomado(NFe.Components.HAmargosaBA.ConsultarNfseServicoTomadoRequest request) {
            return base.Channel.ConsultarNfseServicoTomado(request);
        }
        
        public string ConsultarNfseServicoTomado(string nfseCabecMsg, string nfseDadosMsg) {
            NFe.Components.HAmargosaBA.ConsultarNfseServicoTomadoRequest inValue = new NFe.Components.HAmargosaBA.ConsultarNfseServicoTomadoRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            NFe.Components.HAmargosaBA.ConsultarNfseServicoTomadoResponse retVal = ((NFe.Components.HAmargosaBA.Infse)(this)).ConsultarNfseServicoTomado(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.ConsultarNfseServicoTomadoResponse> NFe.Components.HAmargosaBA.Infse.ConsultarNfseServicoTomadoAsync(NFe.Components.HAmargosaBA.ConsultarNfseServicoTomadoRequest request) {
            return base.Channel.ConsultarNfseServicoTomadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.ConsultarNfseServicoTomadoResponse> ConsultarNfseServicoTomadoAsync(string nfseCabecMsg, string nfseDadosMsg) {
            NFe.Components.HAmargosaBA.ConsultarNfseServicoTomadoRequest inValue = new NFe.Components.HAmargosaBA.ConsultarNfseServicoTomadoRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NFe.Components.HAmargosaBA.Infse)(this)).ConsultarNfseServicoTomadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFe.Components.HAmargosaBA.ConsultarNfsePorFaixaResponse NFe.Components.HAmargosaBA.Infse.ConsultarNfsePorFaixa(NFe.Components.HAmargosaBA.ConsultarNfsePorFaixaRequest request) {
            return base.Channel.ConsultarNfsePorFaixa(request);
        }
        
        public string ConsultarNfsePorFaixa(string nfseCabecMsg, string nfseDadosMsg) {
            NFe.Components.HAmargosaBA.ConsultarNfsePorFaixaRequest inValue = new NFe.Components.HAmargosaBA.ConsultarNfsePorFaixaRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            NFe.Components.HAmargosaBA.ConsultarNfsePorFaixaResponse retVal = ((NFe.Components.HAmargosaBA.Infse)(this)).ConsultarNfsePorFaixa(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.ConsultarNfsePorFaixaResponse> NFe.Components.HAmargosaBA.Infse.ConsultarNfsePorFaixaAsync(NFe.Components.HAmargosaBA.ConsultarNfsePorFaixaRequest request) {
            return base.Channel.ConsultarNfsePorFaixaAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.ConsultarNfsePorFaixaResponse> ConsultarNfsePorFaixaAsync(string nfseCabecMsg, string nfseDadosMsg) {
            NFe.Components.HAmargosaBA.ConsultarNfsePorFaixaRequest inValue = new NFe.Components.HAmargosaBA.ConsultarNfsePorFaixaRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NFe.Components.HAmargosaBA.Infse)(this)).ConsultarNfsePorFaixaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFe.Components.HAmargosaBA.IncluirOutrasInformacoesNaNfseResponse NFe.Components.HAmargosaBA.Infse.IncluirOutrasInformacoesNaNfse(NFe.Components.HAmargosaBA.IncluirOutrasInformacoesNaNfseRequest request) {
            return base.Channel.IncluirOutrasInformacoesNaNfse(request);
        }
        
        public string IncluirOutrasInformacoesNaNfse(string inscricaoMunicipalPrestador, string numeroNfse, string codigoVerificacao, string outrasInformacoes) {
            NFe.Components.HAmargosaBA.IncluirOutrasInformacoesNaNfseRequest inValue = new NFe.Components.HAmargosaBA.IncluirOutrasInformacoesNaNfseRequest();
            inValue.inscricaoMunicipalPrestador = inscricaoMunicipalPrestador;
            inValue.numeroNfse = numeroNfse;
            inValue.codigoVerificacao = codigoVerificacao;
            inValue.outrasInformacoes = outrasInformacoes;
            NFe.Components.HAmargosaBA.IncluirOutrasInformacoesNaNfseResponse retVal = ((NFe.Components.HAmargosaBA.Infse)(this)).IncluirOutrasInformacoesNaNfse(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.IncluirOutrasInformacoesNaNfseResponse> NFe.Components.HAmargosaBA.Infse.IncluirOutrasInformacoesNaNfseAsync(NFe.Components.HAmargosaBA.IncluirOutrasInformacoesNaNfseRequest request) {
            return base.Channel.IncluirOutrasInformacoesNaNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFe.Components.HAmargosaBA.IncluirOutrasInformacoesNaNfseResponse> IncluirOutrasInformacoesNaNfseAsync(string inscricaoMunicipalPrestador, string numeroNfse, string codigoVerificacao, string outrasInformacoes) {
            NFe.Components.HAmargosaBA.IncluirOutrasInformacoesNaNfseRequest inValue = new NFe.Components.HAmargosaBA.IncluirOutrasInformacoesNaNfseRequest();
            inValue.inscricaoMunicipalPrestador = inscricaoMunicipalPrestador;
            inValue.numeroNfse = numeroNfse;
            inValue.codigoVerificacao = codigoVerificacao;
            inValue.outrasInformacoes = outrasInformacoes;
            return ((NFe.Components.HAmargosaBA.Infse)(this)).IncluirOutrasInformacoesNaNfseAsync(inValue);
        }
    }
}
