//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace NFe.Components.br.com.nfeosasco.www.p {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_INotaFiscalEletronicaServico", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestBase))]
    public partial class NotaFiscalEletronicaServico : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EmitirOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelarOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NotaFiscalEletronicaServico() {
            this.Url = global::NFe.Components.Properties.Settings.Default.NFe_Components_br_com_nfeosasco_www_p_NotaFiscalEletronicaServico;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EmitirCompletedEventHandler EmitirCompleted;
        
        /// <remarks/>
        public event CancelarCompletedEventHandler CancelarCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INotaFiscalEletronicaServico/Emitir", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EmissaoNotaFiscalResponse Emitir([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] EmissaoNotaFiscalRequest request) {
            object[] results = this.Invoke("Emitir", new object[] {
                        request});
            return ((EmissaoNotaFiscalResponse)(results[0]));
        }
        
        /// <remarks/>
        public void EmitirAsync(EmissaoNotaFiscalRequest request) {
            this.EmitirAsync(request, null);
        }
        
        /// <remarks/>
        public void EmitirAsync(EmissaoNotaFiscalRequest request, object userState) {
            if ((this.EmitirOperationCompleted == null)) {
                this.EmitirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmitirOperationCompleted);
            }
            this.InvokeAsync("Emitir", new object[] {
                        request}, this.EmitirOperationCompleted, userState);
        }
        
        private void OnEmitirOperationCompleted(object arg) {
            if ((this.EmitirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmitirCompleted(this, new EmitirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INotaFiscalEletronicaServico/Cancelar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CancelamentoNotaFiscalResponse Cancelar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CancelamentoNotaFiscalRequest request) {
            object[] results = this.Invoke("Cancelar", new object[] {
                        request});
            return ((CancelamentoNotaFiscalResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CancelarAsync(CancelamentoNotaFiscalRequest request) {
            this.CancelarAsync(request, null);
        }
        
        /// <remarks/>
        public void CancelarAsync(CancelamentoNotaFiscalRequest request, object userState) {
            if ((this.CancelarOperationCompleted == null)) {
                this.CancelarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelarOperationCompleted);
            }
            this.InvokeAsync("Cancelar", new object[] {
                        request}, this.CancelarOperationCompleted, userState);
        }
        
        private void OnCancelarOperationCompleted(object arg) {
            if ((this.CancelarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelarCompleted(this, new CancelarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    public partial class EmissaoNotaFiscalRequest : RequestBase {
        
        private NotaFiscalDTO notaFiscalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NotaFiscalDTO NotaFiscal {
            get {
                return this.notaFiscalField;
            }
            set {
                this.notaFiscalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Dominio.DataTransferObject.Prestador")]
    public partial class NotaFiscalDTO {
        
        private System.Nullable<decimal> aliquotaField;
        
        private string atividadeField;
        
        private string cEPPrestacaoServicoField;
        
        private string chaveAutenticacaoField;
        
        private string cidadePrestacaoServicoField;
        
        private string enderecoPrestacaoServicoField;
        
        private string estadoPrestacaoServicoField;
        
        private bool homologacaoField;
        
        private string informacoesAdicionaisField;
        
        private bool notificarTomadorPorEmailField;
        
        private bool substituicaoTributariaField;
        
        private PessoaDTO tomadorField;
        
        private bool tomadorEstrangeiroField;
        
        private bool tomadorEstrangeiroFieldSpecified;
        
        private decimal valorField;
        
        private System.Nullable<decimal> valorCSLLField;
        
        private bool valorCSLLFieldSpecified;
        
        private System.Nullable<decimal> valorCofinsField;
        
        private bool valorCofinsFieldSpecified;
        
        private System.Nullable<decimal> valorDeducaoField;
        
        private System.Nullable<decimal> valorINSSField;
        
        private bool valorINSSFieldSpecified;
        
        private System.Nullable<decimal> valorIRField;
        
        private bool valorIRFieldSpecified;
        
        private System.Nullable<decimal> valorOutrosImpostosField;
        
        private bool valorOutrosImpostosFieldSpecified;
        
        private System.Nullable<decimal> valorPisPasepField;
        
        private bool valorPisPasepFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Aliquota {
            get {
                return this.aliquotaField;
            }
            set {
                this.aliquotaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Atividade {
            get {
                return this.atividadeField;
            }
            set {
                this.atividadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CEPPrestacaoServico {
            get {
                return this.cEPPrestacaoServicoField;
            }
            set {
                this.cEPPrestacaoServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ChaveAutenticacao {
            get {
                return this.chaveAutenticacaoField;
            }
            set {
                this.chaveAutenticacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CidadePrestacaoServico {
            get {
                return this.cidadePrestacaoServicoField;
            }
            set {
                this.cidadePrestacaoServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EnderecoPrestacaoServico {
            get {
                return this.enderecoPrestacaoServicoField;
            }
            set {
                this.enderecoPrestacaoServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EstadoPrestacaoServico {
            get {
                return this.estadoPrestacaoServicoField;
            }
            set {
                this.estadoPrestacaoServicoField = value;
            }
        }
        
        /// <remarks/>
        public bool Homologacao {
            get {
                return this.homologacaoField;
            }
            set {
                this.homologacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string InformacoesAdicionais {
            get {
                return this.informacoesAdicionaisField;
            }
            set {
                this.informacoesAdicionaisField = value;
            }
        }
        
        /// <remarks/>
        public bool NotificarTomadorPorEmail {
            get {
                return this.notificarTomadorPorEmailField;
            }
            set {
                this.notificarTomadorPorEmailField = value;
            }
        }
        
        /// <remarks/>
        public bool SubstituicaoTributaria {
            get {
                return this.substituicaoTributariaField;
            }
            set {
                this.substituicaoTributariaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PessoaDTO Tomador {
            get {
                return this.tomadorField;
            }
            set {
                this.tomadorField = value;
            }
        }
        
        /// <remarks/>
        public bool TomadorEstrangeiro {
            get {
                return this.tomadorEstrangeiroField;
            }
            set {
                this.tomadorEstrangeiroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TomadorEstrangeiroSpecified {
            get {
                return this.tomadorEstrangeiroFieldSpecified;
            }
            set {
                this.tomadorEstrangeiroFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ValorCSLL {
            get {
                return this.valorCSLLField;
            }
            set {
                this.valorCSLLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorCSLLSpecified {
            get {
                return this.valorCSLLFieldSpecified;
            }
            set {
                this.valorCSLLFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ValorCofins {
            get {
                return this.valorCofinsField;
            }
            set {
                this.valorCofinsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorCofinsSpecified {
            get {
                return this.valorCofinsFieldSpecified;
            }
            set {
                this.valorCofinsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ValorDeducao {
            get {
                return this.valorDeducaoField;
            }
            set {
                this.valorDeducaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ValorINSS {
            get {
                return this.valorINSSField;
            }
            set {
                this.valorINSSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorINSSSpecified {
            get {
                return this.valorINSSFieldSpecified;
            }
            set {
                this.valorINSSFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ValorIR {
            get {
                return this.valorIRField;
            }
            set {
                this.valorIRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorIRSpecified {
            get {
                return this.valorIRFieldSpecified;
            }
            set {
                this.valorIRFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ValorOutrosImpostos {
            get {
                return this.valorOutrosImpostosField;
            }
            set {
                this.valorOutrosImpostosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorOutrosImpostosSpecified {
            get {
                return this.valorOutrosImpostosFieldSpecified;
            }
            set {
                this.valorOutrosImpostosFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ValorPisPasep {
            get {
                return this.valorPisPasepField;
            }
            set {
                this.valorPisPasepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorPisPasepSpecified {
            get {
                return this.valorPisPasepFieldSpecified;
            }
            set {
                this.valorPisPasepFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Dominio.DataTransferObject.Contribuinte")]
    public partial class PessoaDTO {
        
        private string cNPJField;
        
        private string cPFField;
        
        private string dDDField;
        
        private string emailField;
        
        private EnderecoDTO enderecoField;
        
        private string inscricaoMunicipalField;
        
        private string nomeField;
        
        private string telefoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CNPJ {
            get {
                return this.cNPJField;
            }
            set {
                this.cNPJField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CPF {
            get {
                return this.cPFField;
            }
            set {
                this.cPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DDD {
            get {
                return this.dDDField;
            }
            set {
                this.dDDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EnderecoDTO Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string InscricaoMunicipal {
            get {
                return this.inscricaoMunicipalField;
            }
            set {
                this.inscricaoMunicipalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Dominio.DataTransferObject.Contrbuinte")]
    public partial class EnderecoDTO {
        
        private string bairroField;
        
        private string cEPField;
        
        private string cidadeField;
        
        private string complementoField;
        
        private string estadoField;
        
        private string logradouroField;
        
        private string numeroField;
        
        private string paisField;
        
        private string tipoLogradouroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CEP {
            get {
                return this.cEPField;
            }
            set {
                this.cEPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TipoLogradouro {
            get {
                return this.tipoLogradouroField;
            }
            set {
                this.tipoLogradouroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Dominio.DataTransferObject.Prestador")]
    public partial class NotaFiscalGeradaDTO {
        
        private string autenticadorField;
        
        private string linkField;
        
        private string numeroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Autenticador {
            get {
                return this.autenticadorField;
            }
            set {
                this.autenticadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CancelamentoNotaFiscalResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EmissaoNotaFiscalResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    public partial class ResponseBase {
        
        private bool erroField;
        
        private bool erroFieldSpecified;
        
        private string mensagemErroField;
        
        /// <remarks/>
        public bool Erro {
            get {
                return this.erroField;
            }
            set {
                this.erroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErroSpecified {
            get {
                return this.erroFieldSpecified;
            }
            set {
                this.erroFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MensagemErro {
            get {
                return this.mensagemErroField;
            }
            set {
                this.mensagemErroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    public partial class CancelamentoNotaFiscalResponse : ResponseBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    public partial class EmissaoNotaFiscalResponse : ResponseBase {
        
        private NotaFiscalGeradaDTO notaFiscalGeradaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NotaFiscalGeradaDTO NotaFiscalGerada {
            get {
                return this.notaFiscalGeradaField;
            }
            set {
                this.notaFiscalGeradaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CancelamentoNotaFiscalRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EmissaoNotaFiscalRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    public partial class RequestBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    public partial class CancelamentoNotaFiscalRequest : RequestBase {
        
        private string chaveAutenticacaoField;
        
        private bool homologacaoField;
        
        private string numeroNotaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ChaveAutenticacao {
            get {
                return this.chaveAutenticacaoField;
            }
            set {
                this.chaveAutenticacaoField = value;
            }
        }
        
        /// <remarks/>
        public bool Homologacao {
            get {
                return this.homologacaoField;
            }
            set {
                this.homologacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NumeroNota {
            get {
                return this.numeroNotaField;
            }
            set {
                this.numeroNotaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void EmitirCompletedEventHandler(object sender, EmitirCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmitirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmitirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EmissaoNotaFiscalResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EmissaoNotaFiscalResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void CancelarCompletedEventHandler(object sender, CancelarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CancelamentoNotaFiscalResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CancelamentoNotaFiscalResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591