//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace NFe.Components.br.com.etransparencia.nfehomologacao.h {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ws_nfeSoapBinding", Namespace="NFe")]
    public partial class ws_nfe : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PROCESSARPSOperationCompleted;
        
        private System.Threading.SendOrPostCallback CONSULTANOTASPROTOCOLOOperationCompleted;
        
        private System.Threading.SendOrPostCallback CONSULTAPROTOCOLOOperationCompleted;
        
        private System.Threading.SendOrPostCallback VERFICARPSOperationCompleted;
        
        private System.Threading.SendOrPostCallback CANCELANOTAELETRONICAOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ws_nfe() {
            this.Url = global::NFe.Components.Properties.Settings.Default.NFe_Components_br_com_etransparencia_nfehomologacao_h_ws_nfe;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PROCESSARPSCompletedEventHandler PROCESSARPSCompleted;
        
        /// <remarks/>
        public event CONSULTANOTASPROTOCOLOCompletedEventHandler CONSULTANOTASPROTOCOLOCompleted;
        
        /// <remarks/>
        public event CONSULTAPROTOCOLOCompletedEventHandler CONSULTAPROTOCOLOCompleted;
        
        /// <remarks/>
        public event VERFICARPSCompletedEventHandler VERFICARPSCompleted;
        
        /// <remarks/>
        public event CANCELANOTAELETRONICACompletedEventHandler CANCELANOTAELETRONICACompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("NFeaction/AWS_NFE.PROCESSARPS", RequestElementName="ws_nfe.PROCESSARPS", RequestNamespace="NFe", ResponseElementName="ws_nfe.PROCESSARPSResponse", ResponseNamespace="NFe", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Sdt_processarpsout")]
        public Sdt_ProcessarpsOut PROCESSARPS(Sdt_ProcessarpsIn Sdt_processarpsin) {
            object[] results = this.Invoke("PROCESSARPS", new object[] {
                        Sdt_processarpsin});
            return ((Sdt_ProcessarpsOut)(results[0]));
        }
        
        /// <remarks/>
        public void PROCESSARPSAsync(Sdt_ProcessarpsIn Sdt_processarpsin) {
            this.PROCESSARPSAsync(Sdt_processarpsin, null);
        }
        
        /// <remarks/>
        public void PROCESSARPSAsync(Sdt_ProcessarpsIn Sdt_processarpsin, object userState) {
            if ((this.PROCESSARPSOperationCompleted == null)) {
                this.PROCESSARPSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPROCESSARPSOperationCompleted);
            }
            this.InvokeAsync("PROCESSARPS", new object[] {
                        Sdt_processarpsin}, this.PROCESSARPSOperationCompleted, userState);
        }
        
        private void OnPROCESSARPSOperationCompleted(object arg) {
            if ((this.PROCESSARPSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PROCESSARPSCompleted(this, new PROCESSARPSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("NFeaction/AWS_NFE.CONSULTANOTASPROTOCOLO", RequestElementName="ws_nfe.CONSULTANOTASPROTOCOLO", RequestNamespace="NFe", ResponseElementName="ws_nfe.CONSULTANOTASPROTOCOLOResponse", ResponseNamespace="NFe", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Sdt_consultanotasprotocoloout")]
        public SDT_ConsultaNotasProtocoloOut CONSULTANOTASPROTOCOLO(SDT_ConsultaProtocoloIn Sdt_consultanotasprotocoloin) {
            object[] results = this.Invoke("CONSULTANOTASPROTOCOLO", new object[] {
                        Sdt_consultanotasprotocoloin});
            return ((SDT_ConsultaNotasProtocoloOut)(results[0]));
        }
        
        /// <remarks/>
        public void CONSULTANOTASPROTOCOLOAsync(SDT_ConsultaProtocoloIn Sdt_consultanotasprotocoloin) {
            this.CONSULTANOTASPROTOCOLOAsync(Sdt_consultanotasprotocoloin, null);
        }
        
        /// <remarks/>
        public void CONSULTANOTASPROTOCOLOAsync(SDT_ConsultaProtocoloIn Sdt_consultanotasprotocoloin, object userState) {
            if ((this.CONSULTANOTASPROTOCOLOOperationCompleted == null)) {
                this.CONSULTANOTASPROTOCOLOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCONSULTANOTASPROTOCOLOOperationCompleted);
            }
            this.InvokeAsync("CONSULTANOTASPROTOCOLO", new object[] {
                        Sdt_consultanotasprotocoloin}, this.CONSULTANOTASPROTOCOLOOperationCompleted, userState);
        }
        
        private void OnCONSULTANOTASPROTOCOLOOperationCompleted(object arg) {
            if ((this.CONSULTANOTASPROTOCOLOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CONSULTANOTASPROTOCOLOCompleted(this, new CONSULTANOTASPROTOCOLOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("NFeaction/AWS_NFE.CONSULTAPROTOCOLO", RequestElementName="ws_nfe.CONSULTAPROTOCOLO", RequestNamespace="NFe", ResponseElementName="ws_nfe.CONSULTAPROTOCOLOResponse", ResponseNamespace="NFe", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Sdt_consultaprotocoloout")]
        public SDT_ConsultaProtocoloOut CONSULTAPROTOCOLO(SDT_ConsultaProtocoloIn Sdt_consultaprotocoloin) {
            object[] results = this.Invoke("CONSULTAPROTOCOLO", new object[] {
                        Sdt_consultaprotocoloin});
            return ((SDT_ConsultaProtocoloOut)(results[0]));
        }
        
        /// <remarks/>
        public void CONSULTAPROTOCOLOAsync(SDT_ConsultaProtocoloIn Sdt_consultaprotocoloin) {
            this.CONSULTAPROTOCOLOAsync(Sdt_consultaprotocoloin, null);
        }
        
        /// <remarks/>
        public void CONSULTAPROTOCOLOAsync(SDT_ConsultaProtocoloIn Sdt_consultaprotocoloin, object userState) {
            if ((this.CONSULTAPROTOCOLOOperationCompleted == null)) {
                this.CONSULTAPROTOCOLOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCONSULTAPROTOCOLOOperationCompleted);
            }
            this.InvokeAsync("CONSULTAPROTOCOLO", new object[] {
                        Sdt_consultaprotocoloin}, this.CONSULTAPROTOCOLOOperationCompleted, userState);
        }
        
        private void OnCONSULTAPROTOCOLOOperationCompleted(object arg) {
            if ((this.CONSULTAPROTOCOLOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CONSULTAPROTOCOLOCompleted(this, new CONSULTAPROTOCOLOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("NFeaction/AWS_NFE.VERFICARPS", RequestElementName="ws_nfe.VERFICARPS", RequestNamespace="NFe", ResponseElementName="ws_nfe.VERFICARPSResponse", ResponseNamespace="NFe", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Sdt_processarpsout")]
        public Sdt_ProcessarpsOut VERFICARPS(Sdt_ProcessarpsIn Sdt_processarpsin) {
            object[] results = this.Invoke("VERFICARPS", new object[] {
                        Sdt_processarpsin});
            return ((Sdt_ProcessarpsOut)(results[0]));
        }
        
        /// <remarks/>
        public void VERFICARPSAsync(Sdt_ProcessarpsIn Sdt_processarpsin) {
            this.VERFICARPSAsync(Sdt_processarpsin, null);
        }
        
        /// <remarks/>
        public void VERFICARPSAsync(Sdt_ProcessarpsIn Sdt_processarpsin, object userState) {
            if ((this.VERFICARPSOperationCompleted == null)) {
                this.VERFICARPSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVERFICARPSOperationCompleted);
            }
            this.InvokeAsync("VERFICARPS", new object[] {
                        Sdt_processarpsin}, this.VERFICARPSOperationCompleted, userState);
        }
        
        private void OnVERFICARPSOperationCompleted(object arg) {
            if ((this.VERFICARPSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VERFICARPSCompleted(this, new VERFICARPSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("NFeaction/AWS_NFE.CANCELANOTAELETRONICA", RequestElementName="ws_nfe.CANCELANOTAELETRONICA", RequestNamespace="NFe", ResponseElementName="ws_nfe.CANCELANOTAELETRONICAResponse", ResponseNamespace="NFe", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Sdt_retornocancelanfe")]
        public Sdt_RetornoCancelaNFE CANCELANOTAELETRONICA(Sdt_CancelaNFE Sdt_cancelanfe) {
            object[] results = this.Invoke("CANCELANOTAELETRONICA", new object[] {
                        Sdt_cancelanfe});
            return ((Sdt_RetornoCancelaNFE)(results[0]));
        }
        
        /// <remarks/>
        public void CANCELANOTAELETRONICAAsync(Sdt_CancelaNFE Sdt_cancelanfe) {
            this.CANCELANOTAELETRONICAAsync(Sdt_cancelanfe, null);
        }
        
        /// <remarks/>
        public void CANCELANOTAELETRONICAAsync(Sdt_CancelaNFE Sdt_cancelanfe, object userState) {
            if ((this.CANCELANOTAELETRONICAOperationCompleted == null)) {
                this.CANCELANOTAELETRONICAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCANCELANOTAELETRONICAOperationCompleted);
            }
            this.InvokeAsync("CANCELANOTAELETRONICA", new object[] {
                        Sdt_cancelanfe}, this.CANCELANOTAELETRONICAOperationCompleted, userState);
        }
        
        private void OnCANCELANOTAELETRONICAOperationCompleted(object arg) {
            if ((this.CANCELANOTAELETRONICACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CANCELANOTAELETRONICACompleted(this, new CANCELANOTAELETRONICACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="NFe")]
    public partial class Sdt_ProcessarpsIn {
        
        private Sdt_ProcessarpsInLogin loginField;
        
        private Sdt_ProcessarpsInSDTRPS sDTRPSField;
        
        /// <remarks/>
        public Sdt_ProcessarpsInLogin Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public Sdt_ProcessarpsInSDTRPS SDTRPS {
            get {
                return this.sDTRPSField;
            }
            set {
                this.sDTRPSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Sdt_ProcessarpsIn.Login", Namespace="NFe")]
    public partial class Sdt_ProcessarpsInLogin {
        
        private string codigoUsuarioField;
        
        private string codigoContribuinteField;
        
        /// <remarks/>
        public string CodigoUsuario {
            get {
                return this.codigoUsuarioField;
            }
            set {
                this.codigoUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoContribuinte {
            get {
                return this.codigoContribuinteField;
            }
            set {
                this.codigoContribuinteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Sdt_RetornoCancelaNFE.Message", Namespace="NFe")]
    public partial class Sdt_RetornoCancelaNFEMessage {
        
        private string idField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="NFe")]
    public partial class Sdt_RetornoCancelaNFE {
        
        private bool retornoField;
        
        private Sdt_RetornoCancelaNFEMessage[] messagesField;
        
        /// <remarks/>
        public bool Retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Message", IsNullable=false)]
        public Sdt_RetornoCancelaNFEMessage[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Sdt_CancelaNFE.Nota", Namespace="NFe")]
    public partial class Sdt_CancelaNFENota {
        
        private string serieNotaField;
        
        private int numeroNotaField;
        
        private string serieRPSField;
        
        private int numeroRpsField;
        
        private double valorNotaField;
        
        private string motivoCancelamentoField;
        
        private string podeCancelarGuiaField;
        
        /// <remarks/>
        public string SerieNota {
            get {
                return this.serieNotaField;
            }
            set {
                this.serieNotaField = value;
            }
        }
        
        /// <remarks/>
        public int NumeroNota {
            get {
                return this.numeroNotaField;
            }
            set {
                this.numeroNotaField = value;
            }
        }
        
        /// <remarks/>
        public string SerieRPS {
            get {
                return this.serieRPSField;
            }
            set {
                this.serieRPSField = value;
            }
        }
        
        /// <remarks/>
        public int NumeroRps {
            get {
                return this.numeroRpsField;
            }
            set {
                this.numeroRpsField = value;
            }
        }
        
        /// <remarks/>
        public double ValorNota {
            get {
                return this.valorNotaField;
            }
            set {
                this.valorNotaField = value;
            }
        }
        
        /// <remarks/>
        public string MotivoCancelamento {
            get {
                return this.motivoCancelamentoField;
            }
            set {
                this.motivoCancelamentoField = value;
            }
        }
        
        /// <remarks/>
        public string PodeCancelarGuia {
            get {
                return this.podeCancelarGuiaField;
            }
            set {
                this.podeCancelarGuiaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Sdt_CancelaNFE.Login", Namespace="NFe")]
    public partial class Sdt_CancelaNFELogin {
        
        private string codigoUsuarioField;
        
        private string codigoContribuinteField;
        
        /// <remarks/>
        public string CodigoUsuario {
            get {
                return this.codigoUsuarioField;
            }
            set {
                this.codigoUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoContribuinte {
            get {
                return this.codigoContribuinteField;
            }
            set {
                this.codigoContribuinteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="NFe")]
    public partial class Sdt_CancelaNFE {
        
        private Sdt_CancelaNFELogin loginField;
        
        private Sdt_CancelaNFENota notaField;
        
        /// <remarks/>
        public Sdt_CancelaNFELogin Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public Sdt_CancelaNFENota Nota {
            get {
                return this.notaField;
            }
            set {
                this.notaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SDT_ConsultaProtocoloOut.Message", Namespace="NFe")]
    public partial class SDT_ConsultaProtocoloOutMessage {
        
        private string idField;
        
        private sbyte typeField;
        
        private string descriptionField;
        
        private int linErrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public sbyte Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int LinErr {
            get {
                return this.linErrField;
            }
            set {
                this.linErrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="NFe")]
    public partial class SDT_ConsultaProtocoloOut {
        
        private bool retornoField;
        
        private sbyte prtXStsField;
        
        private string prtCSerRpsField;
        
        private long prtCRps_1Field;
        
        private long prtCRps_2Field;
        
        private System.Nullable<System.DateTime> prtLPrcIniField;
        
        private System.Nullable<System.DateTime> prtLFinGrvField;
        
        private int pnfCNfe_1Field;
        
        private int pnfCnfe_2Field;
        
        private SDT_ConsultaProtocoloOutMessage[] messagesField;
        
        /// <remarks/>
        public bool Retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
            }
        }
        
        /// <remarks/>
        public sbyte PrtXSts {
            get {
                return this.prtXStsField;
            }
            set {
                this.prtXStsField = value;
            }
        }
        
        /// <remarks/>
        public string PrtCSerRps {
            get {
                return this.prtCSerRpsField;
            }
            set {
                this.prtCSerRpsField = value;
            }
        }
        
        /// <remarks/>
        public long PrtCRps_1 {
            get {
                return this.prtCRps_1Field;
            }
            set {
                this.prtCRps_1Field = value;
            }
        }
        
        /// <remarks/>
        public long PrtCRps_2 {
            get {
                return this.prtCRps_2Field;
            }
            set {
                this.prtCRps_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> PrtLPrcIni {
            get {
                return this.prtLPrcIniField;
            }
            set {
                this.prtLPrcIniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> PrtLFinGrv {
            get {
                return this.prtLFinGrvField;
            }
            set {
                this.prtLFinGrvField = value;
            }
        }
        
        /// <remarks/>
        public int PnfCNfe_1 {
            get {
                return this.pnfCNfe_1Field;
            }
            set {
                this.pnfCNfe_1Field = value;
            }
        }
        
        /// <remarks/>
        public int PnfCnfe_2 {
            get {
                return this.pnfCnfe_2Field;
            }
            set {
                this.pnfCnfe_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Message", IsNullable=false)]
        public SDT_ConsultaProtocoloOutMessage[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SDT_ConsultaNotasProtocoloOut.XML_Notas.Reg90", Namespace="NFe")]
    public partial class SDT_ConsultaNotasProtocoloOutXML_NotasReg90 {
        
        private int qtdRegNormalField;
        
        private double valorNFSField;
        
        private double valorISSField;
        
        private double valorDedField;
        
        private double valorIssRetField;
        
        private int qtdReg30Field;
        
        private double valorTributosField;
        
        /// <remarks/>
        public int QtdRegNormal {
            get {
                return this.qtdRegNormalField;
            }
            set {
                this.qtdRegNormalField = value;
            }
        }
        
        /// <remarks/>
        public double ValorNFS {
            get {
                return this.valorNFSField;
            }
            set {
                this.valorNFSField = value;
            }
        }
        
        /// <remarks/>
        public double ValorISS {
            get {
                return this.valorISSField;
            }
            set {
                this.valorISSField = value;
            }
        }
        
        /// <remarks/>
        public double ValorDed {
            get {
                return this.valorDedField;
            }
            set {
                this.valorDedField = value;
            }
        }
        
        /// <remarks/>
        public double ValorIssRet {
            get {
                return this.valorIssRetField;
            }
            set {
                this.valorIssRetField = value;
            }
        }
        
        /// <remarks/>
        public int QtdReg30 {
            get {
                return this.qtdReg30Field;
            }
            set {
                this.qtdReg30Field = value;
            }
        }
        
        /// <remarks/>
        public double ValorTributos {
            get {
                return this.valorTributosField;
            }
            set {
                this.valorTributosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SDT_ConsultaNotasProtocoloOut.XML_Notas.Reg20Item.Reg30Item", Namespace="NFe")]
    public partial class SDT_ConsultaNotasProtocoloOutXML_NotasReg20ItemReg30Item {
        
        private string tributoSiglaField;
        
        private double tributoAliquotaField;
        
        private double tributoValorField;
        
        /// <remarks/>
        public string TributoSigla {
            get {
                return this.tributoSiglaField;
            }
            set {
                this.tributoSiglaField = value;
            }
        }
        
        /// <remarks/>
        public double TributoAliquota {
            get {
                return this.tributoAliquotaField;
            }
            set {
                this.tributoAliquotaField = value;
            }
        }
        
        /// <remarks/>
        public double TributoValor {
            get {
                return this.tributoValorField;
            }
            set {
                this.tributoValorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SDT_ConsultaNotasProtocoloOut.XML_Notas.Reg20Item", Namespace="NFe")]
    public partial class SDT_ConsultaNotasProtocoloOutXML_NotasReg20Item {
        
        private string tipoNfField;
        
        private int numNfField;
        
        private string serNfField;
        
        private string dtEmiNfField;
        
        private string dtHrGerNfField;
        
        private string codVernfField;
        
        private int numRpsField;
        
        private string serRpsField;
        
        private string dtEmiRpsField;
        
        private string tipoCpfCnpjPreField;
        
        private string cpfCnpjPreField;
        
        private string razSocPreField;
        
        private string logPreField;
        
        private string numEndPreField;
        
        private string complEndPreField;
        
        private string bairroPreField;
        
        private string munPreField;
        
        private string siglaUFPreField;
        
        private int cepPreField;
        
        private string emailPreField;
        
        private string tipoTribPreField;
        
        private string dtAdeSNField;
        
        private double alqIssSNField;
        
        private sbyte sitNfField;
        
        private string dataCncNfField;
        
        private string motivoCncNfField;
        
        private string tipoCpfCnpjTomField;
        
        private string cpfCnpjTomField;
        
        private string razSocTomField;
        
        private string logTomField;
        
        private string numEndTomField;
        
        private string complEndTomField;
        
        private string bairroTomField;
        
        private string munTomField;
        
        private string siglaUFTomField;
        
        private int cepTomField;
        
        private string eMailTomField;
        
        private string logLocPreField;
        
        private string numEndLocPreField;
        
        private string complEndLocPreField;
        
        private string bairroLocPreField;
        
        private string munLocPreField;
        
        private string siglaUFLocpreField;
        
        private int cepLocPreField;
        
        private string codSrvField;
        
        private string discrSrvField;
        
        private double vlNFSField;
        
        private double vlDedField;
        
        private string discrDedField;
        
        private double vlBasCalcField;
        
        private double alqIssField;
        
        private double vlIssField;
        
        private double vlIssRetField;
        
        private SDT_ConsultaNotasProtocoloOutXML_NotasReg20ItemReg30Item[] reg30Field;
        
        /// <remarks/>
        public string TipoNf {
            get {
                return this.tipoNfField;
            }
            set {
                this.tipoNfField = value;
            }
        }
        
        /// <remarks/>
        public int NumNf {
            get {
                return this.numNfField;
            }
            set {
                this.numNfField = value;
            }
        }
        
        /// <remarks/>
        public string SerNf {
            get {
                return this.serNfField;
            }
            set {
                this.serNfField = value;
            }
        }
        
        /// <remarks/>
        public string DtEmiNf {
            get {
                return this.dtEmiNfField;
            }
            set {
                this.dtEmiNfField = value;
            }
        }
        
        /// <remarks/>
        public string DtHrGerNf {
            get {
                return this.dtHrGerNfField;
            }
            set {
                this.dtHrGerNfField = value;
            }
        }
        
        /// <remarks/>
        public string CodVernf {
            get {
                return this.codVernfField;
            }
            set {
                this.codVernfField = value;
            }
        }
        
        /// <remarks/>
        public int NumRps {
            get {
                return this.numRpsField;
            }
            set {
                this.numRpsField = value;
            }
        }
        
        /// <remarks/>
        public string SerRps {
            get {
                return this.serRpsField;
            }
            set {
                this.serRpsField = value;
            }
        }
        
        /// <remarks/>
        public string DtEmiRps {
            get {
                return this.dtEmiRpsField;
            }
            set {
                this.dtEmiRpsField = value;
            }
        }
        
        /// <remarks/>
        public string TipoCpfCnpjPre {
            get {
                return this.tipoCpfCnpjPreField;
            }
            set {
                this.tipoCpfCnpjPreField = value;
            }
        }
        
        /// <remarks/>
        public string CpfCnpjPre {
            get {
                return this.cpfCnpjPreField;
            }
            set {
                this.cpfCnpjPreField = value;
            }
        }
        
        /// <remarks/>
        public string RazSocPre {
            get {
                return this.razSocPreField;
            }
            set {
                this.razSocPreField = value;
            }
        }
        
        /// <remarks/>
        public string LogPre {
            get {
                return this.logPreField;
            }
            set {
                this.logPreField = value;
            }
        }
        
        /// <remarks/>
        public string NumEndPre {
            get {
                return this.numEndPreField;
            }
            set {
                this.numEndPreField = value;
            }
        }
        
        /// <remarks/>
        public string ComplEndPre {
            get {
                return this.complEndPreField;
            }
            set {
                this.complEndPreField = value;
            }
        }
        
        /// <remarks/>
        public string BairroPre {
            get {
                return this.bairroPreField;
            }
            set {
                this.bairroPreField = value;
            }
        }
        
        /// <remarks/>
        public string MunPre {
            get {
                return this.munPreField;
            }
            set {
                this.munPreField = value;
            }
        }
        
        /// <remarks/>
        public string SiglaUFPre {
            get {
                return this.siglaUFPreField;
            }
            set {
                this.siglaUFPreField = value;
            }
        }
        
        /// <remarks/>
        public int CepPre {
            get {
                return this.cepPreField;
            }
            set {
                this.cepPreField = value;
            }
        }
        
        /// <remarks/>
        public string EmailPre {
            get {
                return this.emailPreField;
            }
            set {
                this.emailPreField = value;
            }
        }
        
        /// <remarks/>
        public string TipoTribPre {
            get {
                return this.tipoTribPreField;
            }
            set {
                this.tipoTribPreField = value;
            }
        }
        
        /// <remarks/>
        public string DtAdeSN {
            get {
                return this.dtAdeSNField;
            }
            set {
                this.dtAdeSNField = value;
            }
        }
        
        /// <remarks/>
        public double AlqIssSN {
            get {
                return this.alqIssSNField;
            }
            set {
                this.alqIssSNField = value;
            }
        }
        
        /// <remarks/>
        public sbyte SitNf {
            get {
                return this.sitNfField;
            }
            set {
                this.sitNfField = value;
            }
        }
        
        /// <remarks/>
        public string DataCncNf {
            get {
                return this.dataCncNfField;
            }
            set {
                this.dataCncNfField = value;
            }
        }
        
        /// <remarks/>
        public string MotivoCncNf {
            get {
                return this.motivoCncNfField;
            }
            set {
                this.motivoCncNfField = value;
            }
        }
        
        /// <remarks/>
        public string TipoCpfCnpjTom {
            get {
                return this.tipoCpfCnpjTomField;
            }
            set {
                this.tipoCpfCnpjTomField = value;
            }
        }
        
        /// <remarks/>
        public string CpfCnpjTom {
            get {
                return this.cpfCnpjTomField;
            }
            set {
                this.cpfCnpjTomField = value;
            }
        }
        
        /// <remarks/>
        public string RazSocTom {
            get {
                return this.razSocTomField;
            }
            set {
                this.razSocTomField = value;
            }
        }
        
        /// <remarks/>
        public string LogTom {
            get {
                return this.logTomField;
            }
            set {
                this.logTomField = value;
            }
        }
        
        /// <remarks/>
        public string NumEndTom {
            get {
                return this.numEndTomField;
            }
            set {
                this.numEndTomField = value;
            }
        }
        
        /// <remarks/>
        public string ComplEndTom {
            get {
                return this.complEndTomField;
            }
            set {
                this.complEndTomField = value;
            }
        }
        
        /// <remarks/>
        public string BairroTom {
            get {
                return this.bairroTomField;
            }
            set {
                this.bairroTomField = value;
            }
        }
        
        /// <remarks/>
        public string MunTom {
            get {
                return this.munTomField;
            }
            set {
                this.munTomField = value;
            }
        }
        
        /// <remarks/>
        public string SiglaUFTom {
            get {
                return this.siglaUFTomField;
            }
            set {
                this.siglaUFTomField = value;
            }
        }
        
        /// <remarks/>
        public int CepTom {
            get {
                return this.cepTomField;
            }
            set {
                this.cepTomField = value;
            }
        }
        
        /// <remarks/>
        public string EMailTom {
            get {
                return this.eMailTomField;
            }
            set {
                this.eMailTomField = value;
            }
        }
        
        /// <remarks/>
        public string LogLocPre {
            get {
                return this.logLocPreField;
            }
            set {
                this.logLocPreField = value;
            }
        }
        
        /// <remarks/>
        public string NumEndLocPre {
            get {
                return this.numEndLocPreField;
            }
            set {
                this.numEndLocPreField = value;
            }
        }
        
        /// <remarks/>
        public string ComplEndLocPre {
            get {
                return this.complEndLocPreField;
            }
            set {
                this.complEndLocPreField = value;
            }
        }
        
        /// <remarks/>
        public string BairroLocPre {
            get {
                return this.bairroLocPreField;
            }
            set {
                this.bairroLocPreField = value;
            }
        }
        
        /// <remarks/>
        public string MunLocPre {
            get {
                return this.munLocPreField;
            }
            set {
                this.munLocPreField = value;
            }
        }
        
        /// <remarks/>
        public string SiglaUFLocpre {
            get {
                return this.siglaUFLocpreField;
            }
            set {
                this.siglaUFLocpreField = value;
            }
        }
        
        /// <remarks/>
        public int CepLocPre {
            get {
                return this.cepLocPreField;
            }
            set {
                this.cepLocPreField = value;
            }
        }
        
        /// <remarks/>
        public string CodSrv {
            get {
                return this.codSrvField;
            }
            set {
                this.codSrvField = value;
            }
        }
        
        /// <remarks/>
        public string DiscrSrv {
            get {
                return this.discrSrvField;
            }
            set {
                this.discrSrvField = value;
            }
        }
        
        /// <remarks/>
        public double VlNFS {
            get {
                return this.vlNFSField;
            }
            set {
                this.vlNFSField = value;
            }
        }
        
        /// <remarks/>
        public double VlDed {
            get {
                return this.vlDedField;
            }
            set {
                this.vlDedField = value;
            }
        }
        
        /// <remarks/>
        public string DiscrDed {
            get {
                return this.discrDedField;
            }
            set {
                this.discrDedField = value;
            }
        }
        
        /// <remarks/>
        public double VlBasCalc {
            get {
                return this.vlBasCalcField;
            }
            set {
                this.vlBasCalcField = value;
            }
        }
        
        /// <remarks/>
        public double AlqIss {
            get {
                return this.alqIssField;
            }
            set {
                this.alqIssField = value;
            }
        }
        
        /// <remarks/>
        public double VlIss {
            get {
                return this.vlIssField;
            }
            set {
                this.vlIssField = value;
            }
        }
        
        /// <remarks/>
        public double VlIssRet {
            get {
                return this.vlIssRetField;
            }
            set {
                this.vlIssRetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Reg30Item", IsNullable=false)]
        public SDT_ConsultaNotasProtocoloOutXML_NotasReg20ItemReg30Item[] Reg30 {
            get {
                return this.reg30Field;
            }
            set {
                this.reg30Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SDT_ConsultaNotasProtocoloOut.XML_Notas", Namespace="NFe")]
    public partial class SDT_ConsultaNotasProtocoloOutXML_Notas {
        
        private string cpfCnpjField;
        
        private System.Nullable<System.DateTime> dtIniField;
        
        private System.Nullable<System.DateTime> dtFinField;
        
        private short tipoArqField;
        
        private string versaoField;
        
        private SDT_ConsultaNotasProtocoloOutXML_NotasReg20Item[] reg20Field;
        
        private SDT_ConsultaNotasProtocoloOutXML_NotasReg90 reg90Field;
        
        /// <remarks/>
        public string CpfCnpj {
            get {
                return this.cpfCnpjField;
            }
            set {
                this.cpfCnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> DtIni {
            get {
                return this.dtIniField;
            }
            set {
                this.dtIniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> DtFin {
            get {
                return this.dtFinField;
            }
            set {
                this.dtFinField = value;
            }
        }
        
        /// <remarks/>
        public short TipoArq {
            get {
                return this.tipoArqField;
            }
            set {
                this.tipoArqField = value;
            }
        }
        
        /// <remarks/>
        public string Versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Reg20Item", IsNullable=false)]
        public SDT_ConsultaNotasProtocoloOutXML_NotasReg20Item[] Reg20 {
            get {
                return this.reg20Field;
            }
            set {
                this.reg20Field = value;
            }
        }
        
        /// <remarks/>
        public SDT_ConsultaNotasProtocoloOutXML_NotasReg90 Reg90 {
            get {
                return this.reg90Field;
            }
            set {
                this.reg90Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SDT_ConsultaNotasProtocoloOut.Message", Namespace="NFe")]
    public partial class SDT_ConsultaNotasProtocoloOutMessage {
        
        private string idField;
        
        private sbyte typeField;
        
        private string descriptionField;
        
        private int linErrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public sbyte Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int LinErr {
            get {
                return this.linErrField;
            }
            set {
                this.linErrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="NFe")]
    public partial class SDT_ConsultaNotasProtocoloOut {
        
        private bool retornoField;
        
        private SDT_ConsultaNotasProtocoloOutMessage[] messagesField;
        
        private SDT_ConsultaNotasProtocoloOutXML_Notas xML_NotasField;
        
        /// <remarks/>
        public bool Retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Message", IsNullable=false)]
        public SDT_ConsultaNotasProtocoloOutMessage[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
        
        /// <remarks/>
        public SDT_ConsultaNotasProtocoloOutXML_Notas XML_Notas {
            get {
                return this.xML_NotasField;
            }
            set {
                this.xML_NotasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SDT_ConsultaProtocoloIn.Login", Namespace="NFe")]
    public partial class SDT_ConsultaProtocoloInLogin {
        
        private string codigoUsuarioField;
        
        private string codigoContribuinteField;
        
        /// <remarks/>
        public string CodigoUsuario {
            get {
                return this.codigoUsuarioField;
            }
            set {
                this.codigoUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoContribuinte {
            get {
                return this.codigoContribuinteField;
            }
            set {
                this.codigoContribuinteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="NFe")]
    public partial class SDT_ConsultaProtocoloIn {
        
        private string protocoloField;
        
        private SDT_ConsultaProtocoloInLogin loginField;
        
        /// <remarks/>
        public string Protocolo {
            get {
                return this.protocoloField;
            }
            set {
                this.protocoloField = value;
            }
        }
        
        /// <remarks/>
        public SDT_ConsultaProtocoloInLogin Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Sdt_ProcessarpsOut.Message", Namespace="NFe")]
    public partial class Sdt_ProcessarpsOutMessage {
        
        private string idField;
        
        private sbyte typeField;
        
        private string descriptionField;
        
        private int linErrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public sbyte Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int LinErr {
            get {
                return this.linErrField;
            }
            set {
                this.linErrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="NFe")]
    public partial class Sdt_ProcessarpsOut {
        
        private bool retornoField;
        
        private string protocoloField;
        
        private Sdt_ProcessarpsOutMessage[] messagesField;
        
        /// <remarks/>
        public bool Retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
            }
        }
        
        /// <remarks/>
        public string Protocolo {
            get {
                return this.protocoloField;
            }
            set {
                this.protocoloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Message", IsNullable=false)]
        public Sdt_ProcessarpsOutMessage[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Sdt_ProcessarpsIn.SDTRPS.Reg90", Namespace="NFe")]
    public partial class Sdt_ProcessarpsInSDTRPSReg90 {
        
        private string qtdRegNormalField;
        
        private string valorNFSField;
        
        private string valorISSField;
        
        private string valorDedField;
        
        private string valorIssRetTomField;
        
        private string qtdReg30Field;
        
        private string valorTributosField;
        
        /// <remarks/>
        public string QtdRegNormal {
            get {
                return this.qtdRegNormalField;
            }
            set {
                this.qtdRegNormalField = value;
            }
        }
        
        /// <remarks/>
        public string ValorNFS {
            get {
                return this.valorNFSField;
            }
            set {
                this.valorNFSField = value;
            }
        }
        
        /// <remarks/>
        public string ValorISS {
            get {
                return this.valorISSField;
            }
            set {
                this.valorISSField = value;
            }
        }
        
        /// <remarks/>
        public string ValorDed {
            get {
                return this.valorDedField;
            }
            set {
                this.valorDedField = value;
            }
        }
        
        /// <remarks/>
        public string ValorIssRetTom {
            get {
                return this.valorIssRetTomField;
            }
            set {
                this.valorIssRetTomField = value;
            }
        }
        
        /// <remarks/>
        public string QtdReg30 {
            get {
                return this.qtdReg30Field;
            }
            set {
                this.qtdReg30Field = value;
            }
        }
        
        /// <remarks/>
        public string ValorTributos {
            get {
                return this.valorTributosField;
            }
            set {
                this.valorTributosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Sdt_ProcessarpsIn.SDTRPS.Reg20Item.Reg30Item", Namespace="NFe")]
    public partial class Sdt_ProcessarpsInSDTRPSReg20ItemReg30Item {
        
        private string tributoSiglaField;
        
        private string tributoAliquotaField;
        
        private string tributoValorField;
        
        /// <remarks/>
        public string TributoSigla {
            get {
                return this.tributoSiglaField;
            }
            set {
                this.tributoSiglaField = value;
            }
        }
        
        /// <remarks/>
        public string TributoAliquota {
            get {
                return this.tributoAliquotaField;
            }
            set {
                this.tributoAliquotaField = value;
            }
        }
        
        /// <remarks/>
        public string TributoValor {
            get {
                return this.tributoValorField;
            }
            set {
                this.tributoValorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Sdt_ProcessarpsIn.SDTRPS.Reg20Item", Namespace="NFe")]
    public partial class Sdt_ProcessarpsInSDTRPSReg20Item {
        
        private string tipoNFSField;
        
        private string numRpsField;
        
        private string serRpsField;
        
        private string dtEmiField;
        
        private string retFonteField;
        
        private string codSrvField;
        
        private string discrSrvField;
        
        private string vlNFSField;
        
        private string vlDedField;
        
        private string discrDedField;
        
        private string vlBasCalcField;
        
        private string alqIssField;
        
        private string vlIssField;
        
        private string vlIssRetField;
        
        private string cpfCnpTomField;
        
        private string razSocTomField;
        
        private string tipoLogtomField;
        
        private string logTomField;
        
        private string numEndTomField;
        
        private string complEndTomField;
        
        private string bairroTomField;
        
        private string munTomField;
        
        private string siglaUFTomField;
        
        private string cepTomField;
        
        private string telefoneField;
        
        private string inscricaoMunicipalField;
        
        private string tipoLogLocPreField;
        
        private string logLocPreField;
        
        private string numEndLocPreField;
        
        private string complEndLocPreField;
        
        private string bairroLocPreField;
        
        private string munLocPreField;
        
        private string siglaUFLocpreField;
        
        private string cepLocPreField;
        
        private string email1Field;
        
        private string email2Field;
        
        private string email3Field;
        
        private Sdt_ProcessarpsInSDTRPSReg20ItemReg30Item[] reg30Field;
        
        /// <remarks/>
        public string TipoNFS {
            get {
                return this.tipoNFSField;
            }
            set {
                this.tipoNFSField = value;
            }
        }
        
        /// <remarks/>
        public string NumRps {
            get {
                return this.numRpsField;
            }
            set {
                this.numRpsField = value;
            }
        }
        
        /// <remarks/>
        public string SerRps {
            get {
                return this.serRpsField;
            }
            set {
                this.serRpsField = value;
            }
        }
        
        /// <remarks/>
        public string DtEmi {
            get {
                return this.dtEmiField;
            }
            set {
                this.dtEmiField = value;
            }
        }
        
        /// <remarks/>
        public string RetFonte {
            get {
                return this.retFonteField;
            }
            set {
                this.retFonteField = value;
            }
        }
        
        /// <remarks/>
        public string CodSrv {
            get {
                return this.codSrvField;
            }
            set {
                this.codSrvField = value;
            }
        }
        
        /// <remarks/>
        public string DiscrSrv {
            get {
                return this.discrSrvField;
            }
            set {
                this.discrSrvField = value;
            }
        }
        
        /// <remarks/>
        public string VlNFS {
            get {
                return this.vlNFSField;
            }
            set {
                this.vlNFSField = value;
            }
        }
        
        /// <remarks/>
        public string VlDed {
            get {
                return this.vlDedField;
            }
            set {
                this.vlDedField = value;
            }
        }
        
        /// <remarks/>
        public string DiscrDed {
            get {
                return this.discrDedField;
            }
            set {
                this.discrDedField = value;
            }
        }
        
        /// <remarks/>
        public string VlBasCalc {
            get {
                return this.vlBasCalcField;
            }
            set {
                this.vlBasCalcField = value;
            }
        }
        
        /// <remarks/>
        public string AlqIss {
            get {
                return this.alqIssField;
            }
            set {
                this.alqIssField = value;
            }
        }
        
        /// <remarks/>
        public string VlIss {
            get {
                return this.vlIssField;
            }
            set {
                this.vlIssField = value;
            }
        }
        
        /// <remarks/>
        public string VlIssRet {
            get {
                return this.vlIssRetField;
            }
            set {
                this.vlIssRetField = value;
            }
        }
        
        /// <remarks/>
        public string CpfCnpTom {
            get {
                return this.cpfCnpTomField;
            }
            set {
                this.cpfCnpTomField = value;
            }
        }
        
        /// <remarks/>
        public string RazSocTom {
            get {
                return this.razSocTomField;
            }
            set {
                this.razSocTomField = value;
            }
        }
        
        /// <remarks/>
        public string TipoLogtom {
            get {
                return this.tipoLogtomField;
            }
            set {
                this.tipoLogtomField = value;
            }
        }
        
        /// <remarks/>
        public string LogTom {
            get {
                return this.logTomField;
            }
            set {
                this.logTomField = value;
            }
        }
        
        /// <remarks/>
        public string NumEndTom {
            get {
                return this.numEndTomField;
            }
            set {
                this.numEndTomField = value;
            }
        }
        
        /// <remarks/>
        public string ComplEndTom {
            get {
                return this.complEndTomField;
            }
            set {
                this.complEndTomField = value;
            }
        }
        
        /// <remarks/>
        public string BairroTom {
            get {
                return this.bairroTomField;
            }
            set {
                this.bairroTomField = value;
            }
        }
        
        /// <remarks/>
        public string MunTom {
            get {
                return this.munTomField;
            }
            set {
                this.munTomField = value;
            }
        }
        
        /// <remarks/>
        public string SiglaUFTom {
            get {
                return this.siglaUFTomField;
            }
            set {
                this.siglaUFTomField = value;
            }
        }
        
        /// <remarks/>
        public string CepTom {
            get {
                return this.cepTomField;
            }
            set {
                this.cepTomField = value;
            }
        }
        
        /// <remarks/>
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        public string InscricaoMunicipal {
            get {
                return this.inscricaoMunicipalField;
            }
            set {
                this.inscricaoMunicipalField = value;
            }
        }
        
        /// <remarks/>
        public string TipoLogLocPre {
            get {
                return this.tipoLogLocPreField;
            }
            set {
                this.tipoLogLocPreField = value;
            }
        }
        
        /// <remarks/>
        public string LogLocPre {
            get {
                return this.logLocPreField;
            }
            set {
                this.logLocPreField = value;
            }
        }
        
        /// <remarks/>
        public string NumEndLocPre {
            get {
                return this.numEndLocPreField;
            }
            set {
                this.numEndLocPreField = value;
            }
        }
        
        /// <remarks/>
        public string ComplEndLocPre {
            get {
                return this.complEndLocPreField;
            }
            set {
                this.complEndLocPreField = value;
            }
        }
        
        /// <remarks/>
        public string BairroLocPre {
            get {
                return this.bairroLocPreField;
            }
            set {
                this.bairroLocPreField = value;
            }
        }
        
        /// <remarks/>
        public string MunLocPre {
            get {
                return this.munLocPreField;
            }
            set {
                this.munLocPreField = value;
            }
        }
        
        /// <remarks/>
        public string SiglaUFLocpre {
            get {
                return this.siglaUFLocpreField;
            }
            set {
                this.siglaUFLocpreField = value;
            }
        }
        
        /// <remarks/>
        public string CepLocPre {
            get {
                return this.cepLocPreField;
            }
            set {
                this.cepLocPreField = value;
            }
        }
        
        /// <remarks/>
        public string Email1 {
            get {
                return this.email1Field;
            }
            set {
                this.email1Field = value;
            }
        }
        
        /// <remarks/>
        public string Email2 {
            get {
                return this.email2Field;
            }
            set {
                this.email2Field = value;
            }
        }
        
        /// <remarks/>
        public string Email3 {
            get {
                return this.email3Field;
            }
            set {
                this.email3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Reg30Item", IsNullable=false)]
        public Sdt_ProcessarpsInSDTRPSReg20ItemReg30Item[] Reg30 {
            get {
                return this.reg30Field;
            }
            set {
                this.reg30Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Sdt_ProcessarpsIn.SDTRPS", Namespace="NFe")]
    public partial class Sdt_ProcessarpsInSDTRPS {
        
        private string anoField;
        
        private string mesField;
        
        private string cPFCNPJField;
        
        private string dTIniField;
        
        private string dTFinField;
        
        private string tipoTribField;
        
        private string dtAdeSNField;
        
        private string alqIssSN_IPField;
        
        private string versaoField;
        
        private Sdt_ProcessarpsInSDTRPSReg20Item[] reg20Field;
        
        private Sdt_ProcessarpsInSDTRPSReg90 reg90Field;
        
        /// <remarks/>
        public string Ano {
            get {
                return this.anoField;
            }
            set {
                this.anoField = value;
            }
        }
        
        /// <remarks/>
        public string Mes {
            get {
                return this.mesField;
            }
            set {
                this.mesField = value;
            }
        }
        
        /// <remarks/>
        public string CPFCNPJ {
            get {
                return this.cPFCNPJField;
            }
            set {
                this.cPFCNPJField = value;
            }
        }
        
        /// <remarks/>
        public string DTIni {
            get {
                return this.dTIniField;
            }
            set {
                this.dTIniField = value;
            }
        }
        
        /// <remarks/>
        public string DTFin {
            get {
                return this.dTFinField;
            }
            set {
                this.dTFinField = value;
            }
        }
        
        /// <remarks/>
        public string TipoTrib {
            get {
                return this.tipoTribField;
            }
            set {
                this.tipoTribField = value;
            }
        }
        
        /// <remarks/>
        public string DtAdeSN {
            get {
                return this.dtAdeSNField;
            }
            set {
                this.dtAdeSNField = value;
            }
        }
        
        /// <remarks/>
        public string AlqIssSN_IP {
            get {
                return this.alqIssSN_IPField;
            }
            set {
                this.alqIssSN_IPField = value;
            }
        }
        
        /// <remarks/>
        public string Versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Reg20Item", IsNullable=false)]
        public Sdt_ProcessarpsInSDTRPSReg20Item[] Reg20 {
            get {
                return this.reg20Field;
            }
            set {
                this.reg20Field = value;
            }
        }
        
        /// <remarks/>
        public Sdt_ProcessarpsInSDTRPSReg90 Reg90 {
            get {
                return this.reg90Field;
            }
            set {
                this.reg90Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void PROCESSARPSCompletedEventHandler(object sender, PROCESSARPSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PROCESSARPSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PROCESSARPSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sdt_ProcessarpsOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sdt_ProcessarpsOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CONSULTANOTASPROTOCOLOCompletedEventHandler(object sender, CONSULTANOTASPROTOCOLOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CONSULTANOTASPROTOCOLOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CONSULTANOTASPROTOCOLOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SDT_ConsultaNotasProtocoloOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SDT_ConsultaNotasProtocoloOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CONSULTAPROTOCOLOCompletedEventHandler(object sender, CONSULTAPROTOCOLOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CONSULTAPROTOCOLOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CONSULTAPROTOCOLOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SDT_ConsultaProtocoloOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SDT_ConsultaProtocoloOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void VERFICARPSCompletedEventHandler(object sender, VERFICARPSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VERFICARPSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VERFICARPSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sdt_ProcessarpsOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sdt_ProcessarpsOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CANCELANOTAELETRONICACompletedEventHandler(object sender, CANCELANOTAELETRONICACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CANCELANOTAELETRONICACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CANCELANOTAELETRONICACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sdt_RetornoCancelaNFE Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sdt_RetornoCancelaNFE)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591