### YamlMime:ManagedReference
items:
- uid: Unimake.Business.DFe.Security
  commentId: N:Unimake.Business.DFe.Security
  id: Unimake.Business.DFe.Security
  children:
  - Unimake.Business.DFe.Security.AlgorithmType
  - Unimake.Business.DFe.Security.AssinaturaDigital
  - Unimake.Business.DFe.Security.ClsX509Certificate2Extension
  - Unimake.Business.DFe.Security.CryptographicExceptionHandler
  langs:
  - csharp
  - vb
  name: Unimake.Business.DFe.Security
  nameWithType: Unimake.Business.DFe.Security
  fullName: Unimake.Business.DFe.Security
  type: Namespace
  assemblies:
  - Unimake.Business.DFe
references:
- uid: Unimake.Business.DFe.Security.ClsX509Certificate2Extension
  commentId: T:Unimake.Business.DFe.Security.ClsX509Certificate2Extension
  name: ClsX509Certificate2Extension
  nameWithType: ClsX509Certificate2Extension
  fullName: Unimake.Business.DFe.Security.ClsX509Certificate2Extension
- uid: Unimake.Business.DFe.Security.AssinaturaDigital
  commentId: T:Unimake.Business.DFe.Security.AssinaturaDigital
  name: AssinaturaDigital
  nameWithType: AssinaturaDigital
  fullName: Unimake.Business.DFe.Security.AssinaturaDigital
- uid: Unimake.Business.DFe.Security.AlgorithmType
  commentId: T:Unimake.Business.DFe.Security.AlgorithmType
  parent: Unimake.Business.DFe.Security
  name: AlgorithmType
  nameWithType: AlgorithmType
  fullName: Unimake.Business.DFe.Security.AlgorithmType
- uid: Unimake.Business.DFe.Security.CryptographicExceptionHandler
  commentId: T:Unimake.Business.DFe.Security.CryptographicExceptionHandler
  name: CryptographicExceptionHandler
  nameWithType: CryptographicExceptionHandler
  fullName: Unimake.Business.DFe.Security.CryptographicExceptionHandler
- uid: Unimake.Business.DFe.Security
  commentId: N:Unimake.Business.DFe.Security
  name: Unimake.Business.DFe.Security
  nameWithType: Unimake.Business.DFe.Security
  fullName: Unimake.Business.DFe.Security
