### YamlMime:ManagedReference
items:
- uid: Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf
  commentId: T:Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf
  id: TConsultaConfigUf
  parent: Unimake.Business.DFe.Xml.GNRE
  children:
  - Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.Ambiente
  - Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.Receita
  - Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.UF
  - Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.Versao
  langs:
  - csharp
  - vb
  name: TConsultaConfigUf
  nameWithType: TConsultaConfigUf
  fullName: Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf
  type: Class
  source:
    id: TConsultaConfigUf
    path: D:\projetos\uninfe\trunk\fontes\.NET Standard\Unimake.Business.DFe\Xml\GNRE\TConsultaConfigUf.cs
    startLine: 11
  assemblies:
  - Unimake.Business.DFe
  namespace: Unimake.Business.DFe.Xml.GNRE
  syntax:
    content: >-
      [ComVisible(true)]

      [Serializable]

      public class TConsultaConfigUf : XMLBase
    content.vb: >-
      <ComVisible(True)>

      <Serializable>

      Public Class TConsultaConfigUf
          Inherits XMLBase
  inheritance:
  - System.Object
  - Unimake.Business.DFe.Xml.XMLBase
  inheritedMembers:
  - Unimake.Business.DFe.Xml.XMLBase.NameSpaces
  - Unimake.Business.DFe.Xml.XMLBase.GerarXML
  - Unimake.Business.DFe.Xml.XMLBase.LerXML``1(System.Xml.XmlDocument)
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  attributes:
  - type: System.Runtime.InteropServices.ComVisibleAttribute
    ctor: System.Runtime.InteropServices.ComVisibleAttribute.#ctor(System.Boolean)
    arguments:
    - type: System.Boolean
      value: true
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.Versao
  commentId: P:Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.Versao
  id: Versao
  parent: Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf
  langs:
  - csharp
  - vb
  name: Versao
  nameWithType: TConsultaConfigUf.Versao
  fullName: Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.Versao
  type: Property
  source:
    id: Versao
    path: D:\projetos\uninfe\trunk\fontes\.NET Standard\Unimake.Business.DFe\Xml\GNRE\TConsultaConfigUf.cs
    startLine: 16
  assemblies:
  - Unimake.Business.DFe
  namespace: Unimake.Business.DFe.Xml.GNRE
  syntax:
    content: public string Versao { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Versao As String
  overload: Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.Versao*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.Ambiente
  commentId: P:Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.Ambiente
  id: Ambiente
  parent: Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf
  langs:
  - csharp
  - vb
  name: Ambiente
  nameWithType: TConsultaConfigUf.Ambiente
  fullName: Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.Ambiente
  type: Property
  source:
    id: Ambiente
    path: D:\projetos\uninfe\trunk\fontes\.NET Standard\Unimake.Business.DFe\Xml\GNRE\TConsultaConfigUf.cs
    startLine: 19
  assemblies:
  - Unimake.Business.DFe
  namespace: Unimake.Business.DFe.Xml.GNRE
  syntax:
    content: public TipoAmbiente Ambiente { get; set; }
    parameters: []
    return:
      type: Unimake.Business.DFe.Servicos.TipoAmbiente
    content.vb: Public Property Ambiente As TipoAmbiente
  overload: Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.Ambiente*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.UF
  commentId: P:Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.UF
  id: UF
  parent: Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf
  langs:
  - csharp
  - vb
  name: UF
  nameWithType: TConsultaConfigUf.UF
  fullName: Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.UF
  type: Property
  source:
    id: UF
    path: D:\projetos\uninfe\trunk\fontes\.NET Standard\Unimake.Business.DFe\Xml\GNRE\TConsultaConfigUf.cs
    startLine: 22
  assemblies:
  - Unimake.Business.DFe
  namespace: Unimake.Business.DFe.Xml.GNRE
  syntax:
    content: public UFBrasil UF { get; set; }
    parameters: []
    return:
      type: Unimake.Business.DFe.Servicos.UFBrasil
    content.vb: Public Property UF As UFBrasil
  overload: Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.UF*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.Receita
  commentId: P:Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.Receita
  id: Receita
  parent: Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf
  langs:
  - csharp
  - vb
  name: Receita
  nameWithType: TConsultaConfigUf.Receita
  fullName: Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.Receita
  type: Property
  source:
    id: Receita
    path: D:\projetos\uninfe\trunk\fontes\.NET Standard\Unimake.Business.DFe\Xml\GNRE\TConsultaConfigUf.cs
    startLine: 25
  assemblies:
  - Unimake.Business.DFe
  namespace: Unimake.Business.DFe.Xml.GNRE
  syntax:
    content: public Receita Receita { get; set; }
    parameters: []
    return:
      type: Unimake.Business.DFe.Xml.GNRE.Receita
    content.vb: Public Property Receita As Receita
  overload: Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.Receita*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Unimake.Business.DFe.Xml.GNRE
  commentId: N:Unimake.Business.DFe.Xml.GNRE
  name: Unimake.Business.DFe.Xml.GNRE
  nameWithType: Unimake.Business.DFe.Xml.GNRE
  fullName: Unimake.Business.DFe.Xml.GNRE
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Unimake.Business.DFe.Xml.XMLBase
  commentId: T:Unimake.Business.DFe.Xml.XMLBase
  parent: Unimake.Business.DFe.Xml
  name: XMLBase
  nameWithType: XMLBase
  fullName: Unimake.Business.DFe.Xml.XMLBase
- uid: Unimake.Business.DFe.Xml.XMLBase.NameSpaces
  commentId: P:Unimake.Business.DFe.Xml.XMLBase.NameSpaces
  parent: Unimake.Business.DFe.Xml.XMLBase
  name: NameSpaces
  nameWithType: XMLBase.NameSpaces
  fullName: Unimake.Business.DFe.Xml.XMLBase.NameSpaces
- uid: Unimake.Business.DFe.Xml.XMLBase.GerarXML
  commentId: M:Unimake.Business.DFe.Xml.XMLBase.GerarXML
  parent: Unimake.Business.DFe.Xml.XMLBase
  name: GerarXML()
  nameWithType: XMLBase.GerarXML()
  fullName: Unimake.Business.DFe.Xml.XMLBase.GerarXML()
  spec.csharp:
  - uid: Unimake.Business.DFe.Xml.XMLBase.GerarXML
    name: GerarXML
    nameWithType: XMLBase.GerarXML
    fullName: Unimake.Business.DFe.Xml.XMLBase.GerarXML
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Unimake.Business.DFe.Xml.XMLBase.GerarXML
    name: GerarXML
    nameWithType: XMLBase.GerarXML
    fullName: Unimake.Business.DFe.Xml.XMLBase.GerarXML
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Unimake.Business.DFe.Xml.XMLBase.LerXML``1(System.Xml.XmlDocument)
  commentId: M:Unimake.Business.DFe.Xml.XMLBase.LerXML``1(System.Xml.XmlDocument)
  parent: Unimake.Business.DFe.Xml.XMLBase
  isExternal: true
  name: LerXML<T>(XmlDocument)
  nameWithType: XMLBase.LerXML<T>(XmlDocument)
  fullName: Unimake.Business.DFe.Xml.XMLBase.LerXML<T>(System.Xml.XmlDocument)
  nameWithType.vb: XMLBase.LerXML(Of T)(XmlDocument)
  fullName.vb: Unimake.Business.DFe.Xml.XMLBase.LerXML(Of T)(System.Xml.XmlDocument)
  name.vb: LerXML(Of T)(XmlDocument)
  spec.csharp:
  - uid: Unimake.Business.DFe.Xml.XMLBase.LerXML``1(System.Xml.XmlDocument)
    name: LerXML<T>
    nameWithType: XMLBase.LerXML<T>
    fullName: Unimake.Business.DFe.Xml.XMLBase.LerXML<T>
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Xml.XmlDocument
    name: XmlDocument
    nameWithType: XmlDocument
    fullName: System.Xml.XmlDocument
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Unimake.Business.DFe.Xml.XMLBase.LerXML``1(System.Xml.XmlDocument)
    name: LerXML(Of T)
    nameWithType: XMLBase.LerXML(Of T)
    fullName: Unimake.Business.DFe.Xml.XMLBase.LerXML(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Xml.XmlDocument
    name: XmlDocument
    nameWithType: XmlDocument
    fullName: System.Xml.XmlDocument
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  name: System
  nameWithType: System
  fullName: System
- uid: Unimake.Business.DFe.Xml
  commentId: N:Unimake.Business.DFe.Xml
  name: Unimake.Business.DFe.Xml
  nameWithType: Unimake.Business.DFe.Xml
  fullName: Unimake.Business.DFe.Xml
- uid: Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.Versao*
  commentId: Overload:Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.Versao
  name: Versao
  nameWithType: TConsultaConfigUf.Versao
  fullName: Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.Versao
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.Ambiente*
  commentId: Overload:Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.Ambiente
  name: Ambiente
  nameWithType: TConsultaConfigUf.Ambiente
  fullName: Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.Ambiente
- uid: Unimake.Business.DFe.Servicos.TipoAmbiente
  commentId: T:Unimake.Business.DFe.Servicos.TipoAmbiente
  parent: Unimake.Business.DFe.Servicos
  name: TipoAmbiente
  nameWithType: TipoAmbiente
  fullName: Unimake.Business.DFe.Servicos.TipoAmbiente
- uid: Unimake.Business.DFe.Servicos
  commentId: N:Unimake.Business.DFe.Servicos
  name: Unimake.Business.DFe.Servicos
  nameWithType: Unimake.Business.DFe.Servicos
  fullName: Unimake.Business.DFe.Servicos
- uid: Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.UF*
  commentId: Overload:Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.UF
  name: UF
  nameWithType: TConsultaConfigUf.UF
  fullName: Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.UF
- uid: Unimake.Business.DFe.Servicos.UFBrasil
  commentId: T:Unimake.Business.DFe.Servicos.UFBrasil
  parent: Unimake.Business.DFe.Servicos
  name: UFBrasil
  nameWithType: UFBrasil
  fullName: Unimake.Business.DFe.Servicos.UFBrasil
- uid: Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.Receita*
  commentId: Overload:Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.Receita
  name: Receita
  nameWithType: TConsultaConfigUf.Receita
  fullName: Unimake.Business.DFe.Xml.GNRE.TConsultaConfigUf.Receita
- uid: Unimake.Business.DFe.Xml.GNRE.Receita
  commentId: T:Unimake.Business.DFe.Xml.GNRE.Receita
  parent: Unimake.Business.DFe.Xml.GNRE
  name: Receita
  nameWithType: Receita
  fullName: Unimake.Business.DFe.Xml.GNRE.Receita
