//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFe.Components.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.nfse.erechim.rs.gov.br:8182/NfseService_Homolog/NfseService_Homolog")]
        public string NFe_Components_br_gov_rs_erechim_nfse_www_h_NfseService_Homolog {
            get {
                return ((string)(this["NFe_Components_br_gov_rs_erechim_nfse_www_h_NfseService_Homolog"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.nfse.erechim.rs.gov.br:8182/NfseService/NfseService")]
        public string NFe_Components_br_gov_rs_erechim_nfse_www_p_NfseService {
            get {
                return ((string)(this["NFe_Components_br_gov_rs_erechim_nfse_www_p_NfseService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://testebauru.sigiss.com.br:443/testebauru/ws/sigiss_ws.php")]
        public string NFe_Components_br_com_sigiss_testebauru_h_WebService_SigISS {
            get {
                return ((string)(this["NFe_Components_br_com_sigiss_testebauru_h_WebService_SigISS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bauru.sigiss.com.br:443/bauru/ws/sigiss_ws.php")]
        public string NFe_Components_br_com_sigiss_bauru_p_WebService_SigISS {
            get {
                return ((string)(this["NFe_Components_br_com_sigiss_bauru_p_WebService_SigISS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://botucatu.sigiss.com.br:443/botucatu/ws/sigiss_ws.php")]
        public string NFe_Components_br_com_sigiss_botucatu_p_WebService_SigISS {
            get {
                return ((string)(this["NFe_Components_br_com_sigiss_botucatu_p_WebService_SigISS"]));
            }
        }
    }
}
