copy ..\fontes\uninfe\bin\release\MetroFramework.dll      \\servidor\ftp\sergio\uninfe /y
copy ..\fontes\uninfe\bin\release\NFe.Certificado.dll     \\servidor\ftp\sergio\uninfe /y
copy ..\fontes\uninfe\bin\release\NFe.Components.dll      \\servidor\ftp\sergio\uninfe /y
copy ..\fontes\uninfe\bin\release\NFe.Components.Info.dll \\servidor\ftp\sergio\uninfe /y
copy ..\fontes\uninfe\bin\release\NFe.Components.Wsdl.dll \\servidor\ftp\sergio\uninfe /y
copy ..\fontes\uninfe\bin\release\NFe.ConvertTxt.dll      \\servidor\ftp\sergio\uninfe /y
copy ..\fontes\uninfe\bin\release\NFe.Service.dll         \\servidor\ftp\sergio\uninfe /y
copy ..\fontes\uninfe\bin\release\NFe.Settings.dll        \\servidor\ftp\sergio\uninfe /y
copy ..\fontes\uninfe\bin\release\NFe.Threadings.dll      \\servidor\ftp\sergio\uninfe /y
copy ..\fontes\uninfe\bin\release\NFe.UI.dll              \\servidor\ftp\sergio\uninfe /y
copy ..\fontes\uninfe\bin\release\NFe.Validate.dll        \\servidor\ftp\sergio\uninfe /y
copy ..\fontes\uninfe\bin\release\NFSe.Components.dll     \\servidor\ftp\sergio\uninfe /y
copy ..\fontes\uninfe\bin\release\uninfe.exe              \\servidor\ftp\sergio\uninfe /y